import { SKILL, SKILL_ADJUSTMENT, SKILL_CATEGORY, SKILL_EFFECIENT, SKILL_QUALITY, SKILL_STATUS } from "src/app/models/skill.model";

export const Skills: SKILL[] = [
  {
    id: 's00000001',
    name: '仁世无疆',
    name_en: 'renshiwujiang',
    desc: '对自身及1名友方武将恢复一定兵力（回复率50%，受智力影响），并提高其30%闪避（触发时令所受伤害无效），持续10秒，技能冷却20秒。',
    desc_en: '',
    category: SKILL_CATEGORY.COMMAND,
    level: 1,
    status: SKILL_STATUS.UNKNOWN,
    effecient: [SKILL_EFFECIENT.HEAL, SKILL_EFFECIENT.BUFF],
    adjustment: [SKILL_ADJUSTMENT.INFANTRY, SKILL_ADJUSTMENT.ARCHER, SKILL_ADJUSTMENT.CAVALRY, SKILL_ADJUSTMENT.PIKEMAN],        
    quality: SKILL_QUALITY.S,
    exchangable: false,
    hero: 'h00000001'    
  },
  {
    id: 's00000002',
    name: '神机妙算',
    name_en: 'shenjimiaosuan',
    desc: '（火）对范围内的敌军共造成145%智力伤害，此伤害有额外10%神算几率（触发时智力伤害翻倍）基础概率，并基于自身与每个目标的智力差，每100点可额外提高5%概率，技能冷却20秒。',
    desc_en: '',
    category: SKILL_CATEGORY.COMMAND,
    level: 1,
    status: SKILL_STATUS.UNKNOWN,
    effecient: [SKILL_EFFECIENT.INTELLIGENCE_MULTIPLE],
    adjustment: [SKILL_ADJUSTMENT.INFANTRY, SKILL_ADJUSTMENT.ARCHER, SKILL_ADJUSTMENT.CAVALRY, SKILL_ADJUSTMENT.PIKEMAN],
    quality: SKILL_QUALITY.S,
    exchangable: false,
    hero: 'h00000002'
  },
  {
    id: 's00000003',
    name: '沉桥断水',
    name_en: 'chenqiaoduanshui',
    desc: '对范围内的敌军共造成120%的武力伤害，并提高自身30%的暴击几率（触发时武力伤害翻倍），持续10秒，技能冷却20秒。',
    desc_en: '',
    category: SKILL_CATEGORY.MAIN,
    level: 1,
    status: SKILL_STATUS.UNKNOWN,
    effecient: [SKILL_EFFECIENT.FORCE_MULTIPLE, SKILL_EFFECIENT.CONTROL],
    adjustment: [SKILL_ADJUSTMENT.INFANTRY, SKILL_ADJUSTMENT.ARCHER, SKILL_ADJUSTMENT.CAVALRY, SKILL_ADJUSTMENT.PIKEMAN],
    quality: SKILL_QUALITY.S,
    exchangable: false,
    hero: 'h00000003'
  },
  {
    id: 's00000004',
    name: '威震华夏',
    name_en: 'weizhenhuaxia',
    desc: '对敌方单体武将120%武力伤害，并降低其50点武力及防御，持续10秒，技能冷却20秒。',
    desc_en: '',
    category: SKILL_CATEGORY.MAIN,
    level: 1,
    status: SKILL_STATUS.UNKNOWN,
    effecient: [SKILL_EFFECIENT.FORCE_SINGLE, SKILL_EFFECIENT.DEBUFF],
    adjustment: [SKILL_ADJUSTMENT.INFANTRY, SKILL_ADJUSTMENT.ARCHER, SKILL_ADJUSTMENT.CAVALRY, SKILL_ADJUSTMENT.PIKEMAN],
    quality: SKILL_QUALITY.S,
    exchangable: false,
    hero: 'h00000004'
  },
  {
    id: 's00000005',
    name: '孤胆七出',
    name_en: 'gudanqichu',
    desc: '对敌方单体武将进行最多7段攻击，每次随机造成30%武力或智力伤害，技能冷却20秒。',
    desc_en: '',
    category: SKILL_CATEGORY.PASSIVE,
    level: 1,
    status: SKILL_STATUS.UNKNOWN,
    effecient: [SKILL_EFFECIENT.INTELLIGENCE_SINGLE, SKILL_EFFECIENT.FORCE_SINGLE],
    adjustment: [SKILL_ADJUSTMENT.INFANTRY, SKILL_ADJUSTMENT.ARCHER, SKILL_ADJUSTMENT.CAVALRY, SKILL_ADJUSTMENT.PIKEMAN],
    quality: SKILL_QUALITY.S,
    exchangable: false,
    hero: 'h00000005'
  },
  {
    id: 's00000006',
    name: '狂勇陷战',
    name_en: 'kuangyongxianzhan',
    desc: '对范围内的敌军共造成120%武力伤害，并提高自身20%励军（基于造成的武力伤害回复一定兵力），持续10秒，技能冷却20秒。',
    desc_en: '',
    category: SKILL_CATEGORY.MAIN,
    level: 1,
    status: SKILL_STATUS.UNKNOWN,
    effecient: [SKILL_EFFECIENT.FORCE_MULTIPLE],
    adjustment: [SKILL_ADJUSTMENT.INFANTRY, SKILL_ADJUSTMENT.ARCHER, SKILL_ADJUSTMENT.CAVALRY, SKILL_ADJUSTMENT.PIKEMAN],
    quality: SKILL_QUALITY.S,
    exchangable: false,
    hero: 'h00000006'
  },
  {
    id: 's00000007',
    name: '穿石没羽',
    name_en: 'chuanshimoyu',
    desc: '对范围内的敌军共造成80%的武力伤害，并对其施加溃散（持续武力伤害，总伤害率55%），持续20秒，技能冷却20秒。',
    desc_en: '',
    category: SKILL_CATEGORY.MAIN,
    level: 1,
    status: SKILL_STATUS.UNKNOWN,
    effecient: [SKILL_EFFECIENT.FORCE_MULTIPLE],
    adjustment: [SKILL_ADJUSTMENT.INFANTRY, SKILL_ADJUSTMENT.ARCHER, SKILL_ADJUSTMENT.CAVALRY, SKILL_ADJUSTMENT.PIKEMAN],
    quality: SKILL_QUALITY.S,
    exchangable: false,
    hero: 'h00000007'
  },
  {
    id: 's00000008',
    name: '锦耀飞雄',
    name_en: 'jinyaofeixiong',
    desc: '对范围内的敌军共造成120%武力伤害，并提高自身30%连击伤害，持续10秒。',
    desc_en: '',
    category: SKILL_CATEGORY.MAIN,
    level: 1,
    status: SKILL_STATUS.UNKNOWN,
    effecient: [SKILL_EFFECIENT.FORCE_MULTIPLE, SKILL_EFFECIENT.BUFF],
    adjustment: [SKILL_ADJUSTMENT.INFANTRY, SKILL_ADJUSTMENT.ARCHER, SKILL_ADJUSTMENT.CAVALRY, SKILL_ADJUSTMENT.PIKEMAN],
    quality: SKILL_QUALITY.S,
    exchangable: false,
    hero: 'h00000008'
  },
  {
    id: 's00000009',
    name: '擒生踏伏',
    name_en: 'qinshengtafu',
    desc: '对范围内的敌军共造成120%（240%）武力伤害，并使其受到连击伤害提高20%（40%)，持续10秒。',
    desc_en: '',
    category: SKILL_CATEGORY.MAIN,
    level: 1,
    status: SKILL_STATUS.UNKNOWN,
    effecient: [SKILL_EFFECIENT.FORCE_MULTIPLE],
    adjustment: [SKILL_ADJUSTMENT.INFANTRY, SKILL_ADJUSTMENT.ARCHER, SKILL_ADJUSTMENT.CAVALRY, SKILL_ADJUSTMENT.PIKEMAN],
    quality: SKILL_QUALITY.S,
    exchangable: false,
    hero: 'h00000009'
  },
  {
    id: 's00000010',
    name: '智勇双全',
    name_en: 'zhiyongshuangquan',
    desc: '对范围内的敌军共造成武力伤害95%、智力伤害95%，技能冷却20秒。',
    desc_en: '',
    category: SKILL_CATEGORY.MAIN,
    level: 1,
    status: SKILL_STATUS.UNKNOWN,
    effecient: [SKILL_EFFECIENT.INTELLIGENCE_MULTIPLE, SKILL_EFFECIENT.FORCE_MULTIPLE],
    adjustment: [SKILL_ADJUSTMENT.INFANTRY, SKILL_ADJUSTMENT.ARCHER, SKILL_ADJUSTMENT.CAVALRY, SKILL_ADJUSTMENT.PIKEMAN],
    quality: SKILL_QUALITY.S,
    exchangable: false,
    hero: 'h00000010'
  },
  {
    id: 's00000011',
    name: '走马荐士',
    name_en: 'zoumajianshi',
    desc: '净化（移除目标负面状态）2名友方武将身上的负面状态，并提高其10%主动技能施放概率，持续10秒，技能冷却20秒。',
    desc_en: '',
    category: SKILL_CATEGORY.MAIN,
    level: 1,
    status: SKILL_STATUS.UNKNOWN,
    effecient: [SKILL_EFFECIENT.BUFF],
    adjustment: [SKILL_ADJUSTMENT.INFANTRY, SKILL_ADJUSTMENT.ARCHER, SKILL_ADJUSTMENT.CAVALRY, SKILL_ADJUSTMENT.PIKEMAN],
    quality: SKILL_QUALITY.S,
    exchangable: false,
    hero: 'h00000011'
  },
  {
    id: 's00000012',
    name: '断头将军',
    name_en: 'duantoujiangjun',
    desc: '对范围内的敌军共造成120%武力伤害，并降低其20%连击技能伤害，持续10秒，技能冷却20秒。',
    desc_en: '',
    category: SKILL_CATEGORY.MAIN,
    level: 1,
    status: SKILL_STATUS.UNKNOWN,
    effecient: [SKILL_EFFECIENT.FORCE_MULTIPLE, SKILL_EFFECIENT.DEBUFF],
    adjustment: [SKILL_ADJUSTMENT.INFANTRY, SKILL_ADJUSTMENT.ARCHER, SKILL_ADJUSTMENT.CAVALRY, SKILL_ADJUSTMENT.PIKEMAN],
    quality: SKILL_QUALITY.S,
    exchangable: false,
    hero: 'h00000012'
  },
  {
    id: 's00000013',
    name: '凤雏先生',
    name_en: 'fengchuxiansheng',
    desc: '（火）对范围内敌军共造成120%智力伤害，并提高我方全体武将10%智力伤害，持续10秒，技能冷却20秒。',
    desc_en: '',
    category: SKILL_CATEGORY.MAIN,
    level: 1,
    status: SKILL_STATUS.UNKNOWN,
    effecient: [SKILL_EFFECIENT.INTELLIGENCE_MULTIPLE, SKILL_EFFECIENT.BUFF],
    adjustment: [SKILL_ADJUSTMENT.INFANTRY, SKILL_ADJUSTMENT.ARCHER, SKILL_ADJUSTMENT.CAVALRY, SKILL_ADJUSTMENT.PIKEMAN],
    quality: SKILL_QUALITY.S,
    exchangable: false,
    hero: 'h00000013'
  },
  {
    id: 's00000014',
    name: '铁骑凤魄',
    name_en: 'tiejifengpo',
    desc: '对范围内的敌军共造成135%武力伤害，技能冷却20秒。',
    desc_en: '',
    category: SKILL_CATEGORY.MAIN,
    level: 1,
    status: SKILL_STATUS.UNKNOWN,
    effecient: [SKILL_EFFECIENT.FORCE_MULTIPLE],
    adjustment: [SKILL_ADJUSTMENT.INFANTRY, SKILL_ADJUSTMENT.ARCHER, SKILL_ADJUSTMENT.CAVALRY, SKILL_ADJUSTMENT.PIKEMAN],
    quality: SKILL_QUALITY.A,
    exchangable: false,
    hero: 'h00000014'
  },
  {
    id: 's00000015',
    name: '燕勇遗风',
    name_en: 'yanyongyifeng',
    desc: '对范围内的敌军共造成100%智力伤害，15%概率对其施加力竭（无法造成伤害），持续10秒，技能冷却20秒。',
    desc_en: '',
    category: SKILL_CATEGORY.MAIN,
    level: 1,
    status: SKILL_STATUS.UNKNOWN,
    effecient: [SKILL_EFFECIENT.INTELLIGENCE_MULTIPLE, SKILL_EFFECIENT.DEBUFF],
    adjustment: [SKILL_ADJUSTMENT.INFANTRY, SKILL_ADJUSTMENT.ARCHER, SKILL_ADJUSTMENT.CAVALRY, SKILL_ADJUSTMENT.PIKEMAN],
    quality: SKILL_QUALITY.A,
    exchangable: false,
    hero: 'h00000015'
  },
  {
    id: 's00000016',
    name: '智藏清流',
    name_en: 'zhizangqingliu',
    desc: '（水）对范围内的敌军共造成100%智力伤害，并降低其智力伤害20%，持续10秒，技能冷却20秒。',
    desc_en: '',
    category: SKILL_CATEGORY.MAIN,
    level: 1,
    status: SKILL_STATUS.UNKNOWN,
    effecient: [SKILL_EFFECIENT.INTELLIGENCE_MULTIPLE, SKILL_EFFECIENT.DEBUFF],
    adjustment: [SKILL_ADJUSTMENT.INFANTRY, SKILL_ADJUSTMENT.ARCHER, SKILL_ADJUSTMENT.CAVALRY, SKILL_ADJUSTMENT.PIKEMAN],
    quality: SKILL_QUALITY.A,
    exchangable: false,
    hero: 'h00000016'
  },
  {
    id: 's00000017',
    name: '龙断之登',
    name_en: 'longduanzhideng',
    desc: '对范围内的敌军共造成135%智力伤害，技能冷却20秒。',
    desc_en: '',
    category: SKILL_CATEGORY.MAIN,
    level: 1,
    status: SKILL_STATUS.UNKNOWN,
    effecient: [SKILL_EFFECIENT.INTELLIGENCE_MULTIPLE],
    adjustment: [SKILL_ADJUSTMENT.INFANTRY, SKILL_ADJUSTMENT.ARCHER, SKILL_ADJUSTMENT.CAVALRY, SKILL_ADJUSTMENT.PIKEMAN],
    quality: SKILL_QUALITY.A,
    exchangable: false,
    hero: 'h00000017'
  },
  {
    id: 's00000018',
    name: '昭烈皇后',
    name_en: 'zhaoliehuanghou',
    desc: '净化（移除目标负面状态）2名友方武将，并对其恢复一定兵力（回复率50%，受智力影响），技能冷却20秒。',
    desc_en: '',
    category: SKILL_CATEGORY.MAIN,
    level: 1,
    status: SKILL_STATUS.UNKNOWN,
    effecient: [SKILL_EFFECIENT.HEAL, SKILL_EFFECIENT.BUFF],
    adjustment: [SKILL_ADJUSTMENT.INFANTRY, SKILL_ADJUSTMENT.ARCHER, SKILL_ADJUSTMENT.CAVALRY, SKILL_ADJUSTMENT.PIKEMAN],
    quality: SKILL_QUALITY.A,
    exchangable: false,
    hero: 'h00000018'
  },
  {
    id: 's00000019',
    name: '关刀雪仇',
    name_en: 'guandaoxuechou',
    desc: '对范围内的敌军共造成135%武力伤害，技能冷却20秒。',
    desc_en: '',
    category: SKILL_CATEGORY.MAIN,
    level: 1,
    status: SKILL_STATUS.UNKNOWN,
    effecient: [SKILL_EFFECIENT.FORCE_MULTIPLE],
    adjustment: [SKILL_ADJUSTMENT.INFANTRY, SKILL_ADJUSTMENT.ARCHER, SKILL_ADJUSTMENT.CAVALRY, SKILL_ADJUSTMENT.PIKEMAN],
    quality: SKILL_QUALITY.A,
    exchangable: false,
    hero: 'h00000019'
  },
  {
    id: 's00000020',
    name: '武圣虎子',
    name_en: 'wushenghuzi',
    desc: '对范围内的敌军共造成135%武力伤害，技能冷却20秒。',
    desc_en: '',
    category: SKILL_CATEGORY.MAIN,
    level: 1,
    status: SKILL_STATUS.UNKNOWN,
    effecient: [SKILL_EFFECIENT.FORCE_MULTIPLE],
    adjustment: [SKILL_ADJUSTMENT.INFANTRY, SKILL_ADJUSTMENT.ARCHER, SKILL_ADJUSTMENT.CAVALRY, SKILL_ADJUSTMENT.PIKEMAN],
    quality: SKILL_QUALITY.A,
    exchangable: false,
    hero: 'h00000020'
  },
  {
    id: 's00000021',
    name: '传魂燕勇',
    name_en: 'chuanhunyanyong',
    desc: '对范围内的敌军共造成135%武力伤害，技能冷却20秒。',
    desc_en: '',
    category: SKILL_CATEGORY.MAIN,
    level: 1,
    status: SKILL_STATUS.UNKNOWN,
    effecient: [SKILL_EFFECIENT.FORCE_MULTIPLE],
    adjustment: [SKILL_ADJUSTMENT.INFANTRY, SKILL_ADJUSTMENT.ARCHER, SKILL_ADJUSTMENT.CAVALRY, SKILL_ADJUSTMENT.PIKEMAN],
    quality: SKILL_QUALITY.A,
    exchangable: false,
    hero: 'h00000021'
  },
  {
    id: 's00000022',
    name: '无貌隐秀',
    name_en: 'wumaoyinxiu',
    desc: '（水）对范围内的敌军共造成120%智力伤害，并降低其20%智力伤害，持续10秒，技能冷却20秒。',
    desc_en: '',
    category: SKILL_CATEGORY.MAIN,
    level: 1,
    status: SKILL_STATUS.UNKNOWN,
    effecient: [SKILL_EFFECIENT.INTELLIGENCE_MULTIPLE, SKILL_EFFECIENT.DEBUFF],
    adjustment: [SKILL_ADJUSTMENT.INFANTRY, SKILL_ADJUSTMENT.ARCHER, SKILL_ADJUSTMENT.CAVALRY, SKILL_ADJUSTMENT.PIKEMAN],
    quality: SKILL_QUALITY.S,
    exchangable: false,
    hero: 'h00000022'
  },
  {
    id: 's00000023',
    name: '飞阵琼芳',
    name_en: 'feizhenxiongfang',
    desc: '对范围内的敌军共造成120%武力伤害，并提高自身30%武力伤害，持续10秒，技能冷却20秒。',
    desc_en: '',
    category: SKILL_CATEGORY.MAIN,
    level: 1,
    status: SKILL_STATUS.UNKNOWN,
    effecient: [SKILL_EFFECIENT.FORCE_MULTIPLE, SKILL_EFFECIENT.BUFF],
    adjustment: [SKILL_ADJUSTMENT.INFANTRY, SKILL_ADJUSTMENT.ARCHER, SKILL_ADJUSTMENT.CAVALRY, SKILL_ADJUSTMENT.PIKEMAN],
    quality: SKILL_QUALITY.S,
    exchangable: false,
    hero: 'h00000023'
  },
  {
    id: 's00000024',
    name: '武圣虎女',
    name_en: 'wushenghunv',
    desc: '对范围内的敌军共造成120%武力伤害，自身兵力低于50%时，使自身受到伤害降低50%，持续10秒，技能冷却20秒。',
    desc_en: '',
    category: SKILL_CATEGORY.MAIN,
    level: 1,
    status: SKILL_STATUS.UNKNOWN,
    effecient: [SKILL_EFFECIENT.FORCE_MULTIPLE, SKILL_EFFECIENT.BUFF],
    adjustment: [SKILL_ADJUSTMENT.INFANTRY, SKILL_ADJUSTMENT.ARCHER, SKILL_ADJUSTMENT.CAVALRY, SKILL_ADJUSTMENT.PIKEMAN],
    quality: SKILL_QUALITY.S,
    exchangable: false,
    hero: 'h00000024'
  },
  {
    id: 's00000025',
    name: '安乐庸君',
    name_en: 'anleyongjun',
    desc: '对自身及友方非蜀势力武将恢复一定兵力（回复率80%，受智力影响），技能冷却20秒。',
    desc_en: '',
    category: SKILL_CATEGORY.MAIN,
    level: 1,
    status: SKILL_STATUS.UNKNOWN,
    effecient: [SKILL_EFFECIENT.HEAL],
    adjustment: [SKILL_ADJUSTMENT.INFANTRY, SKILL_ADJUSTMENT.ARCHER, SKILL_ADJUSTMENT.CAVALRY, SKILL_ADJUSTMENT.PIKEMAN],
    quality: SKILL_QUALITY.S,
    exchangable: false,
    hero: 'h00000025'
  },
  {
    id: 's00000026',
    name: '辅国翼主',
    name_en: 'fuguoyizhu',
    desc: '对范围内的敌军共造成120%智力伤害，50%概率使随机1名我方武将获得1次抵挡（免疫1次主动技能、连击技能伤害），持续10秒，技能冷却20秒。',
    desc_en: '',
    category: SKILL_CATEGORY.MAIN,
    level: 1,
    status: SKILL_STATUS.UNKNOWN,
    effecient: [SKILL_EFFECIENT.INTELLIGENCE_MULTIPLE, SKILL_EFFECIENT.BUFF],
    adjustment: [SKILL_ADJUSTMENT.INFANTRY, SKILL_ADJUSTMENT.ARCHER, SKILL_ADJUSTMENT.CAVALRY, SKILL_ADJUSTMENT.PIKEMAN],
    quality: SKILL_QUALITY.S,
    exchangable: false,
    hero: 'h00000026'
  },
  {
    id: 's00000027',
    name: '优游谈客',
    name_en: 'youyoutanke',
    desc: '对范围内的敌军共造成120%智力伤害，并降低其10%主动技能施放概率，持续10秒，技能冷却20秒。',
    desc_en: '',
    category: SKILL_CATEGORY.MAIN,
    level: 1,
    status: SKILL_STATUS.UNKNOWN,
    effecient: [SKILL_EFFECIENT.INTELLIGENCE_MULTIPLE, SKILL_EFFECIENT.DEBUFF],
    adjustment: [SKILL_ADJUSTMENT.INFANTRY, SKILL_ADJUSTMENT.ARCHER, SKILL_ADJUSTMENT.CAVALRY, SKILL_ADJUSTMENT.PIKEMAN],
    quality: SKILL_QUALITY.S,
    exchangable: false,
    hero: 'h00000027'
  },
  {
    id: 's00000028',
    name: '常胜将军',
    name_en: 'changshengjiangjun',
    desc: '提高自身50%武力伤害，持续10秒，技能冷却20秒。',
    desc_en: '',
    category: SKILL_CATEGORY.MAIN,
    level: 1,
    status: SKILL_STATUS.UNKNOWN,
    effecient: [SKILL_EFFECIENT.BUFF],
    adjustment: [SKILL_ADJUSTMENT.INFANTRY, SKILL_ADJUSTMENT.ARCHER, SKILL_ADJUSTMENT.CAVALRY, SKILL_ADJUSTMENT.PIKEMAN],
    quality: SKILL_QUALITY.S,
    exchangable: false,
    hero: 'h00000028'
  },
  {
    id: 's00000029',
    name: '魏武之治',
    name_en: 'weiwuzhizhi',
    desc: '对范围内的敌军共造成120%智力伤害，并提高2名友方武将50点武力、智力，持续10秒，技能冷却20秒。',
    desc_en: '',
    category: SKILL_CATEGORY.MAIN,
    level: 1,
    status: SKILL_STATUS.UNKNOWN,
    effecient: [SKILL_EFFECIENT.INTELLIGENCE_MULTIPLE, SKILL_EFFECIENT.BUFF],
    adjustment: [SKILL_ADJUSTMENT.INFANTRY, SKILL_ADJUSTMENT.ARCHER, SKILL_ADJUSTMENT.CAVALRY, SKILL_ADJUSTMENT.PIKEMAN],
    quality: SKILL_QUALITY.S,
    exchangable: false,
    hero: 'h00000029'
  },
  {
    id: 's00000030',
    name: '魁杰冢虎',
    name_en: 'kuijiezhonghu',
    desc: '对范围内的敌军共造成120%智力伤害，并提高自身30%的神算几率（触发时智力伤害翻倍），持续10秒，技能冷却20秒。',
    desc_en: '',
    category: SKILL_CATEGORY.MAIN,
    level: 1,
    status: SKILL_STATUS.UNKNOWN,
    effecient: [SKILL_EFFECIENT.INTELLIGENCE_MULTIPLE, SKILL_EFFECIENT.BUFF],
    adjustment: [SKILL_ADJUSTMENT.INFANTRY, SKILL_ADJUSTMENT.ARCHER, SKILL_ADJUSTMENT.CAVALRY, SKILL_ADJUSTMENT.PIKEMAN],
    quality: SKILL_QUALITY.S,
    exchangable: false,
    hero: 'h00000030'
  },
  {
    id: 's00000031',
    name: '背水一战',
    name_en: 'beishuiyizhan',
    desc: '对范围内的敌军共造成120%武力伤害，并提高1名友方武将100点防御，持续10秒，技能冷却20秒。',
    desc_en: '',
    category: SKILL_CATEGORY.MAIN,
    level: 1,
    status: SKILL_STATUS.UNKNOWN,
    effecient: [SKILL_EFFECIENT.FORCE_MULTIPLE, SKILL_EFFECIENT.BUFF],
    adjustment: [SKILL_ADJUSTMENT.INFANTRY, SKILL_ADJUSTMENT.ARCHER, SKILL_ADJUSTMENT.CAVALRY, SKILL_ADJUSTMENT.PIKEMAN],
    quality: SKILL_QUALITY.S,
    exchangable: false,
    hero: 'h00000031'
  },
  {
    id: 's00000032',
    name: '独目苍狼',
    name_en: 'dumucanglang',
    desc: '（雷）对范围内的敌军共造成160%武力伤害，并对其施加禁疗（无法回复兵力），持续10秒，技能冷却20秒。',
    desc_en: '',
    category: SKILL_CATEGORY.MAIN,
    level: 1,
    status: SKILL_STATUS.UNKNOWN,
    effecient: [SKILL_EFFECIENT.FORCE_MULTIPLE, SKILL_EFFECIENT.DEBUFF],
    adjustment: [SKILL_ADJUSTMENT.INFANTRY, SKILL_ADJUSTMENT.ARCHER, SKILL_ADJUSTMENT.CAVALRY, SKILL_ADJUSTMENT.PIKEMAN],
    quality: SKILL_QUALITY.S,
    exchangable: false,
    hero: 'h00000032'
  },
  {
    id: 's00000033',
    name: '天妒鬼才',
    name_en: 'tianduguicai',
    desc: '对范围内的敌军共造成2段75%智力伤害，此次伤害对骑兵武将提高40%，技能冷却20秒。',
    desc_en: '',
    category: SKILL_CATEGORY.MAIN,
    level: 1,
    status: SKILL_STATUS.UNKNOWN,
    effecient: [SKILL_EFFECIENT.INTELLIGENCE_MULTIPLE],
    adjustment: [SKILL_ADJUSTMENT.INFANTRY, SKILL_ADJUSTMENT.ARCHER, SKILL_ADJUSTMENT.CAVALRY, SKILL_ADJUSTMENT.PIKEMAN],
    quality: SKILL_QUALITY.S,
    exchangable: false,
    hero: 'h00000033'
  },
  {
    id: 's00000035',
    name: '亚父之风',
    name_en: 'yafuzhifeng',
    desc: '对范围内的敌军共造成120%武力伤害并对其施加风罡（持续风属性智力伤害，总伤害率30%）持续2-秒，并提高自身100点武力，持续10秒，技能冷却20秒。',
    desc_en: '',
    category: SKILL_CATEGORY.MAIN,
    level: 1,
    status: SKILL_STATUS.UNKNOWN,
    effecient: [SKILL_EFFECIENT.FORCE_MULTIPLE, SKILL_EFFECIENT.BUFF, SKILL_EFFECIENT.DEBUFF],
    adjustment: [SKILL_ADJUSTMENT.INFANTRY, SKILL_ADJUSTMENT.ARCHER, SKILL_ADJUSTMENT.CAVALRY, SKILL_ADJUSTMENT.PIKEMAN],
    quality: SKILL_QUALITY.S,
    exchangable: false,
    hero: 'h00000035'
  },
  {
    id: 's00000036',
    name: '陷坚履险',
    name_en: 'xianjianlvxian',
    desc: '对范围内的敌军共造成80武力伤害，并对其施加风罡（持续风属性智力伤害，总伤害率55%），持续10秒，技能冷却20秒。',
    desc_en: '',
    category: SKILL_CATEGORY.MAIN,
    level: 1,
    status: SKILL_STATUS.UNKNOWN,
    effecient: [SKILL_EFFECIENT.FORCE_MULTIPLE, SKILL_EFFECIENT.INTELLIGENCE_MULTIPLE],
    adjustment: [SKILL_ADJUSTMENT.INFANTRY, SKILL_ADJUSTMENT.ARCHER, SKILL_ADJUSTMENT.CAVALRY, SKILL_ADJUSTMENT.PIKEMAN],
    quality: SKILL_QUALITY.S,
    exchangable: false,
    hero: 'h00000036'
  },
  {
    id: 's00000037',
    name: '逐虎过涧',
    name_en: 'zhuhuguojian',
    desc: '对范围内的敌军共造成2段60%武力伤害，并提高我方全体武将50点防御，持续10秒，技能冷却20秒。',
    desc_en: '',
    category: SKILL_CATEGORY.MAIN,
    level: 1,
    status: SKILL_STATUS.UNKNOWN,
    effecient: [SKILL_EFFECIENT.FORCE_MULTIPLE, SKILL_EFFECIENT.BUFF],
    adjustment: [SKILL_ADJUSTMENT.INFANTRY, SKILL_ADJUSTMENT.ARCHER, SKILL_ADJUSTMENT.CAVALRY, SKILL_ADJUSTMENT.PIKEMAN],
    quality: SKILL_QUALITY.S,
    exchangable: false,
    hero: 'h00000037'
  },
  {
    id: 's00000038',
    name: '王佐凛肃',
    name_en: 'wangzuolinsu',
    desc: '对范围内的敌军共造成120%智力伤害，25%概率对其施加沉默（无法使用主动技能），持续10秒，技能冷却20秒。',
    desc_en: '',
    category: SKILL_CATEGORY.MAIN,
    level: 1,
    status: SKILL_STATUS.UNKNOWN,
    effecient: [SKILL_EFFECIENT.INTELLIGENCE_MULTIPLE, SKILL_EFFECIENT.CONTROL],
    adjustment: [SKILL_ADJUSTMENT.INFANTRY, SKILL_ADJUSTMENT.ARCHER, SKILL_ADJUSTMENT.CAVALRY, SKILL_ADJUSTMENT.PIKEMAN],
    quality: SKILL_QUALITY.S,
    exchangable: false,
    hero: 'h00000038'
  },
  {
    id: 's00000039',
    name: '虎步疾趋',
    name_en: 'hubujiqu',
    desc: '对敌方单体武将造成120%武力伤害，并降低其武力100点，持续10秒，技能冷却20秒。',
    desc_en: '',
    category: SKILL_CATEGORY.MAIN,
    level: 1,
    status: SKILL_STATUS.UNKNOWN,
    effecient: [SKILL_EFFECIENT.FORCE_SINGLE, SKILL_EFFECIENT.DEBUFF],
    adjustment: [SKILL_ADJUSTMENT.INFANTRY, SKILL_ADJUSTMENT.ARCHER, SKILL_ADJUSTMENT.CAVALRY, SKILL_ADJUSTMENT.PIKEMAN],
    quality: SKILL_QUALITY.S,
    exchangable: false,
    hero: 'h00000039'
  },
  {
    id: 's00000040',
    name: '白马将军',
    name_en: 'baimajiangjun',
    desc: '对范围内的敌军共造成120%武力伤害，并提高我方全体骑兵武将20%防御，持续10秒，技能冷却20秒。',
    desc_en: '',
    category: SKILL_CATEGORY.MAIN,
    level: 1,
    status: SKILL_STATUS.UNKNOWN,
    effecient: [SKILL_EFFECIENT.FORCE_MULTIPLE, SKILL_EFFECIENT.BUFF],
    adjustment: [SKILL_ADJUSTMENT.INFANTRY, SKILL_ADJUSTMENT.ARCHER, SKILL_ADJUSTMENT.CAVALRY, SKILL_ADJUSTMENT.PIKEMAN],
    quality: SKILL_QUALITY.S,
    exchangable: false,
    hero: 'h00000040'
  },
  {
    id: 's00000041',
    name: '诛心乱武',
    name_en: 'zhuxinluanwu',
    desc: '（火）对范围内的敌军共造成80%智力伤害并对其施加焚烧（持续火属性智力伤害，总伤害率55%），持续20秒，技能冷却20秒。',
    desc_en: '',
    category: SKILL_CATEGORY.MAIN,
    level: 1,
    status: SKILL_STATUS.UNKNOWN,
    effecient: [SKILL_EFFECIENT.INTELLIGENCE_MULTIPLE],
    adjustment: [SKILL_ADJUSTMENT.INFANTRY, SKILL_ADJUSTMENT.ARCHER, SKILL_ADJUSTMENT.CAVALRY, SKILL_ADJUSTMENT.PIKEMAN],
    quality: SKILL_QUALITY.S,
    exchangable: false,
    hero: 'h00000041'
  },
  {
    id: 's00000042',
    name: '洪毅奋武',
    name_en: 'hongyifenwu',
    desc: '对范围内的敌军共造成135%武力伤害，并对自身施加免疫缴械，持续10秒，技能冷却20秒。',
    desc_en: '',
    category: SKILL_CATEGORY.MAIN,
    level: 1,
    status: SKILL_STATUS.UNKNOWN,
    effecient: [SKILL_EFFECIENT.FORCE_MULTIPLE, SKILL_EFFECIENT.BUFF],
    adjustment: [SKILL_ADJUSTMENT.INFANTRY, SKILL_ADJUSTMENT.ARCHER, SKILL_ADJUSTMENT.CAVALRY, SKILL_ADJUSTMENT.PIKEMAN],
    quality: SKILL_QUALITY.S,
    exchangable: false,
    hero: 'h00000042'
  },
  {
    id: 's00000043',
    name: '虎痴狂胆',
    name_en: 'huchikuangdan',
    desc: '（火）对范围内的敌军共造成120%武力伤害，并提高自身3%连击技能触发概率，持续10秒，技能冷却20秒。',
    desc_en: '',
    category: SKILL_CATEGORY.MAIN,
    level: 1,
    status: SKILL_STATUS.UNKNOWN,
    effecient: [SKILL_EFFECIENT.FORCE_MULTIPLE, SKILL_EFFECIENT.BUFF],
    adjustment: [SKILL_ADJUSTMENT.INFANTRY, SKILL_ADJUSTMENT.ARCHER, SKILL_ADJUSTMENT.CAVALRY, SKILL_ADJUSTMENT.PIKEMAN],
    quality: SKILL_QUALITY.S,
    exchangable: false,
    hero: 'h00000043'
  },
  {
    id: 's00000044',
    name: '奋强突固',
    name_en: 'fenqiangtugu',
    desc: '对范围内的敌军共造成120%武力伤害，并降低其20%防御，持续10秒，技能冷却20秒。',
    desc_en: '',
    category: SKILL_CATEGORY.MAIN,
    level: 1,
    status: SKILL_STATUS.UNKNOWN,
    effecient: [SKILL_EFFECIENT.FORCE_MULTIPLE, SKILL_EFFECIENT.DEBUFF],
    adjustment: [SKILL_ADJUSTMENT.INFANTRY, SKILL_ADJUSTMENT.ARCHER, SKILL_ADJUSTMENT.CAVALRY, SKILL_ADJUSTMENT.PIKEMAN],
    quality: SKILL_QUALITY.S,
    exchangable: false,
    hero: 'h00000044'
  },
  {
    id: 's00000045',
    name: '裹毡履险',
    name_en: 'guozhanlvxian',
    desc: '对范围内敌军造成120%智力伤害，并降低其10%全属性（武力、智力、防御和攻速）持续10秒，技能冷却20秒。',
    desc_en: '',
    category: SKILL_CATEGORY.MAIN,
    level: 1,
    status: SKILL_STATUS.UNKNOWN,
    effecient: [SKILL_EFFECIENT.INTELLIGENCE_MULTIPLE, SKILL_EFFECIENT.DEBUFF],
    adjustment: [SKILL_ADJUSTMENT.INFANTRY, SKILL_ADJUSTMENT.ARCHER, SKILL_ADJUSTMENT.CAVALRY, SKILL_ADJUSTMENT.PIKEMAN],
    quality: SKILL_QUALITY.S,
    exchangable: false,
    hero: 'h00000045'
  },
  {
    id: 's00000046',
    name: '立颂黄初',
    name_en: 'lisonghuangchu',
    desc: '对范围内的敌军共造成120%智力伤害，30%概率对其施加缴械（无法普通攻击），持续10秒，技能冷却20秒。',
    desc_en: '',
    category: SKILL_CATEGORY.MAIN,
    level: 1,
    status: SKILL_STATUS.UNKNOWN,
    effecient: [SKILL_EFFECIENT.INTELLIGENCE_MULTIPLE, SKILL_EFFECIENT.CONTROL],
    adjustment: [SKILL_ADJUSTMENT.INFANTRY, SKILL_ADJUSTMENT.ARCHER, SKILL_ADJUSTMENT.CAVALRY, SKILL_ADJUSTMENT.PIKEMAN],
    quality: SKILL_QUALITY.S,
    exchangable: false,
    hero: 'h00000046'
  },
  {
    id: 's00000047',
    name: '旷世威王',
    name_en: 'kuangshiweiwang',
    desc: '对范围内敌军造成120%武力伤害，并降低其50点防御，持续10秒，技能冷却20秒。',
    desc_en: '',
    category: SKILL_CATEGORY.MAIN,
    level: 1,
    status: SKILL_STATUS.UNKNOWN,
    effecient: [SKILL_EFFECIENT.FORCE_MULTIPLE, SKILL_EFFECIENT.DEBUFF],
    adjustment: [SKILL_ADJUSTMENT.INFANTRY, SKILL_ADJUSTMENT.ARCHER, SKILL_ADJUSTMENT.CAVALRY, SKILL_ADJUSTMENT.PIKEMAN],
    quality: SKILL_QUALITY.S,
    exchangable: false,
    hero: 'h00000047'
  },
  {
    id: 's00000048',
    name: '洛水梦影',
    name_en: 'luoshuimengying',
    desc: '对范围内的敌军共造成120%智力伤害，并降低其10%伤害，持续全场（最多叠加4次），技能冷却20秒。',
    desc_en: '',
    category: SKILL_CATEGORY.MAIN,
    level: 1,
    status: SKILL_STATUS.UNKNOWN,
    effecient: [SKILL_EFFECIENT.INTELLIGENCE_MULTIPLE, SKILL_EFFECIENT.DEBUFF],
    adjustment: [SKILL_ADJUSTMENT.INFANTRY, SKILL_ADJUSTMENT.ARCHER, SKILL_ADJUSTMENT.CAVALRY, SKILL_ADJUSTMENT.PIKEMAN],
    quality: SKILL_QUALITY.S,
    exchangable: false,
    hero: 'h00000048'
  },
  {
    id: 's00000049',
    name: '十二奇策',
    name_en: 'shierqice',
    desc: '对范围内的敌军共造成135%智力伤害，技能冷却20秒。',
    desc_en: '',
    category: SKILL_CATEGORY.MAIN,
    level: 1,
    status: SKILL_STATUS.UNKNOWN,
    effecient: [SKILL_EFFECIENT.INTELLIGENCE_MULTIPLE],
    adjustment: [SKILL_ADJUSTMENT.INFANTRY, SKILL_ADJUSTMENT.ARCHER, SKILL_ADJUSTMENT.CAVALRY, SKILL_ADJUSTMENT.PIKEMAN],
    quality: SKILL_QUALITY.A,
    exchangable: false,
    hero: 'h00000049'
  },
  {
    id: 's00000050',
    name: '指鹿为马',
    name_en: 'zhiluweima',
    desc: '对范围内的敌军共造成135%智力伤害，技能冷却20秒。',
    desc_en: '',
    category: SKILL_CATEGORY.MAIN,
    level: 1,
    status: SKILL_STATUS.UNKNOWN,
    effecient: [SKILL_EFFECIENT.INTELLIGENCE_MULTIPLE],
    adjustment: [SKILL_ADJUSTMENT.INFANTRY, SKILL_ADJUSTMENT.ARCHER, SKILL_ADJUSTMENT.CAVALRY, SKILL_ADJUSTMENT.PIKEMAN],
    quality: SKILL_QUALITY.A,
    exchangable: false,
    hero: 'h00000050'
  },
  {
    id: 's00000051',
    name: '骁骑破垒',
    name_en: 'xiaoqipolei',
    desc: '对范围内的敌军共造成135%武力伤害，技能冷却20秒。',
    desc_en: '',
    category: SKILL_CATEGORY.MAIN,
    level: 1,
    status: SKILL_STATUS.UNKNOWN,
    effecient: [SKILL_EFFECIENT.FORCE_MULTIPLE],
    adjustment: [SKILL_ADJUSTMENT.INFANTRY, SKILL_ADJUSTMENT.ARCHER, SKILL_ADJUSTMENT.CAVALRY, SKILL_ADJUSTMENT.PIKEMAN],
    quality: SKILL_QUALITY.A,
    exchangable: false,
    hero: 'h00000051'
  },
  {
    id: 's00000052',
    name: '齐圣霁月',
    name_en: 'qishengjiyue',
    desc: '对范围内的敌军共造成135%智力伤害，技能冷却20秒。',
    desc_en: '',
    category: SKILL_CATEGORY.MAIN,
    level: 1,
    status: SKILL_STATUS.UNKNOWN,
    effecient: [SKILL_EFFECIENT.INTELLIGENCE_MULTIPLE],
    adjustment: [SKILL_ADJUSTMENT.INFANTRY, SKILL_ADJUSTMENT.ARCHER, SKILL_ADJUSTMENT.CAVALRY, SKILL_ADJUSTMENT.PIKEMAN],
    quality: SKILL_QUALITY.A,
    exchangable: false,
    hero: 'h00000052'
  },
  {
    id: 's00000053',
    name: '扬鞭跃马',
    name_en: 'yangbianyuema',
    desc: '对范围内的敌军共造成135%武力伤害，技能冷却20秒。',
    desc_en: '',
    category: SKILL_CATEGORY.MAIN,
    level: 1,
    status: SKILL_STATUS.UNKNOWN,
    effecient: [SKILL_EFFECIENT.FORCE_MULTIPLE],
    adjustment: [SKILL_ADJUSTMENT.INFANTRY, SKILL_ADJUSTMENT.ARCHER, SKILL_ADJUSTMENT.CAVALRY, SKILL_ADJUSTMENT.PIKEMAN],
    quality: SKILL_QUALITY.A,
    exchangable: false,
    hero: 'h00000053'
  },
  {
    id: 's00000054',
    name: '涂山逸响',
    name_en: 'tushanyixiang',
    desc: '（毒）对范围内的敌军施加中毒（持续毒属性智力伤害，总伤害率82.5%），持续10秒，技能冷却20秒。',
    desc_en: '',
    category: SKILL_CATEGORY.MAIN,
    level: 1,
    status: SKILL_STATUS.UNKNOWN,
    effecient: [SKILL_EFFECIENT.INTELLIGENCE_MULTIPLE],
    adjustment: [SKILL_ADJUSTMENT.INFANTRY, SKILL_ADJUSTMENT.ARCHER, SKILL_ADJUSTMENT.CAVALRY, SKILL_ADJUSTMENT.PIKEMAN],
    quality: SKILL_QUALITY.A,
    exchangable: false,
    hero: 'h00000054'
  },
  {
    id: 's00000055',
    name: '挥戈返日',
    name_en: 'huigefanri',
    desc: '对范围内的敌军共造成135%武力伤害，技能冷却20秒。',
    desc_en: '',
    category: SKILL_CATEGORY.MAIN,
    level: 1,
    status: SKILL_STATUS.UNKNOWN,
    effecient: [SKILL_EFFECIENT.FORCE_MULTIPLE],
    adjustment: [SKILL_ADJUSTMENT.INFANTRY, SKILL_ADJUSTMENT.ARCHER, SKILL_ADJUSTMENT.CAVALRY, SKILL_ADJUSTMENT.PIKEMAN],
    quality: SKILL_QUALITY.A,
    exchangable: false,
    hero: 'h00000055'
  },
  {
    id: 's00000056',
    name: '竭泽而战',
    name_en: 'jiezeerzhan',
    desc: '对范围内的敌军共造成135%武力伤害，技能冷却20秒。',
    desc_en: '',
    category: SKILL_CATEGORY.MAIN,
    level: 1,
    status: SKILL_STATUS.UNKNOWN,
    effecient: [SKILL_EFFECIENT.FORCE_MULTIPLE],
    adjustment: [SKILL_ADJUSTMENT.INFANTRY, SKILL_ADJUSTMENT.ARCHER, SKILL_ADJUSTMENT.CAVALRY, SKILL_ADJUSTMENT.PIKEMAN],
    quality: SKILL_QUALITY.A,
    exchangable: false,
    hero: 'h00000056'
  },
  {
    id: 's00000057',
    name: '姿媚浮生',
    name_en: 'zimeifusheng',
    desc: '（火）对范围内的敌军共造成135%智力伤害，技能冷却20秒。',
    desc_en: '',
    category: SKILL_CATEGORY.MAIN,
    level: 1,
    status: SKILL_STATUS.UNKNOWN,
    effecient: [SKILL_EFFECIENT.INTELLIGENCE_MULTIPLE],
    adjustment: [SKILL_ADJUSTMENT.INFANTRY, SKILL_ADJUSTMENT.ARCHER, SKILL_ADJUSTMENT.CAVALRY, SKILL_ADJUSTMENT.PIKEMAN],
    quality: SKILL_QUALITY.A,
    exchangable: false,
    hero: 'h00000057'
  },
  {
    id: 's00000058',
    name: '斩将搴旗',
    name_en: 'zhanjiangqianqi',
    desc: '对范围内的敌军共造成135%武力伤害，技能冷却20秒。',
    desc_en: '',
    category: SKILL_CATEGORY.MAIN,
    level: 1,
    status: SKILL_STATUS.UNKNOWN,
    effecient: [SKILL_EFFECIENT.FORCE_MULTIPLE],
    adjustment: [SKILL_ADJUSTMENT.INFANTRY, SKILL_ADJUSTMENT.ARCHER, SKILL_ADJUSTMENT.CAVALRY, SKILL_ADJUSTMENT.PIKEMAN],
    quality: SKILL_QUALITY.A,
    exchangable: false,
    hero: 'h00000058'
  },
  {
    id: 's00000059',
    name: '危身连忧',
    name_en: 'weishenlianyou',
    desc: '对范围内的敌军共造成135%武力伤害，技能冷却20秒。',
    desc_en: '',
    category: SKILL_CATEGORY.MAIN,
    level: 1,
    status: SKILL_STATUS.UNKNOWN,
    effecient: [SKILL_EFFECIENT.FORCE_MULTIPLE],
    adjustment: [SKILL_ADJUSTMENT.INFANTRY, SKILL_ADJUSTMENT.ARCHER, SKILL_ADJUSTMENT.CAVALRY, SKILL_ADJUSTMENT.PIKEMAN],
    quality: SKILL_QUALITY.A,
    exchangable: false,
    hero: 'h00000059'
  },
  {
    id: 's00000060',
    name: '攻谋守固',
    name_en: 'gongmoushougu',
    desc: '对范围内的敌军共造成120%智力伤害，并提高自身30%防御，持续10秒，技能冷却20秒。',
    desc_en: '',
    category: SKILL_CATEGORY.MAIN,
    level: 1,
    status: SKILL_STATUS.UNKNOWN,
    effecient: [SKILL_EFFECIENT.INTELLIGENCE_MULTIPLE, SKILL_EFFECIENT.BUFF],
    adjustment: [SKILL_ADJUSTMENT.INFANTRY, SKILL_ADJUSTMENT.ARCHER, SKILL_ADJUSTMENT.CAVALRY, SKILL_ADJUSTMENT.PIKEMAN],
    quality: SKILL_QUALITY.S,
    exchangable: false,
    hero: 'h00000060'
  },
  {
    id: 's00000061',
    name: '十面埋伏',
    name_en: 'shimianmaifu',
    desc: '对敌方单体武将造成120%智力伤害，并降低其30%武力伤害，持续10秒，技能冷却20秒。',
    desc_en: '',
    category: SKILL_CATEGORY.MAIN,
    level: 1,
    status: SKILL_STATUS.UNKNOWN,
    effecient: [SKILL_EFFECIENT.INTELLIGENCE_SINGLE, SKILL_EFFECIENT.DEBUFF],
    adjustment: [SKILL_ADJUSTMENT.INFANTRY, SKILL_ADJUSTMENT.ARCHER, SKILL_ADJUSTMENT.CAVALRY, SKILL_ADJUSTMENT.PIKEMAN],
    quality: SKILL_QUALITY.S,
    exchangable: false,
    hero: 'h00000061'
  },
  {
    id: 's00000062',
    name: '恢奇少君',
    name_en: 'huiqishaojun',
    desc: '对范围内的敌军共造成120%智力伤害，并提高我方魏势力武将50点政治、智力，持续10秒，技能冷却20秒。',
    desc_en: '',
    category: SKILL_CATEGORY.MAIN,
    level: 1,
    status: SKILL_STATUS.UNKNOWN,
    effecient: [SKILL_EFFECIENT.INTELLIGENCE_MULTIPLE, SKILL_EFFECIENT.BUFF],
    adjustment: [SKILL_ADJUSTMENT.INFANTRY, SKILL_ADJUSTMENT.ARCHER, SKILL_ADJUSTMENT.CAVALRY, SKILL_ADJUSTMENT.PIKEMAN],
    quality: SKILL_QUALITY.S,
    exchangable: false,
    hero: 'h00000062'
  },
  {
    id: 's00000063',
    name: '挟术摄统',
    name_en: 'xieshushetong',
    desc: '对范围内的敌军共造成120%智力伤害，并随机提高1名我方武将50点智力、武力，持续10秒，技能冷却20秒。',
    desc_en: '',
    category: SKILL_CATEGORY.MAIN,
    level: 1,
    status: SKILL_STATUS.UNKNOWN,
    effecient: [SKILL_EFFECIENT.INTELLIGENCE_MULTIPLE, SKILL_EFFECIENT.BUFF],
    adjustment: [SKILL_ADJUSTMENT.INFANTRY, SKILL_ADJUSTMENT.ARCHER, SKILL_ADJUSTMENT.CAVALRY, SKILL_ADJUSTMENT.PIKEMAN],
    quality: SKILL_QUALITY.S,
    exchangable: false,
    hero: 'h00000063'
  },
  {
    id: 's00000064',
    name: '仙才风华',
    name_en: 'xiancaifenghua',
    desc: '对范围内的敌军共造成120%智力伤害，并提高自身30%的神算几率（触发时智力伤害翻倍），持续10秒，技能冷却20秒。',
    desc_en: '',
    category: SKILL_CATEGORY.MAIN,
    level: 1,
    status: SKILL_STATUS.UNKNOWN,
    effecient: [SKILL_EFFECIENT.INTELLIGENCE_MULTIPLE, SKILL_EFFECIENT.BUFF],
    adjustment: [SKILL_ADJUSTMENT.INFANTRY, SKILL_ADJUSTMENT.ARCHER, SKILL_ADJUSTMENT.CAVALRY, SKILL_ADJUSTMENT.PIKEMAN],
    quality: SKILL_QUALITY.S,
    exchangable: false,
    hero: 'h00000064'
  },
  {
    id: 's00000065',
    name: '绝情宣穆',
    name_en: 'jueqingxuanmu',
    desc: '对范围内的敌军共造成160%智力伤害，并对其施加禁疗（无法回复兵力），持续10秒，技能冷却20秒。',
    desc_en: '',
    category: SKILL_CATEGORY.MAIN,
    level: 1,
    status: SKILL_STATUS.UNKNOWN,
    effecient: [SKILL_EFFECIENT.INTELLIGENCE_MULTIPLE, SKILL_EFFECIENT.DEBUFF],
    adjustment: [SKILL_ADJUSTMENT.INFANTRY, SKILL_ADJUSTMENT.ARCHER, SKILL_ADJUSTMENT.CAVALRY, SKILL_ADJUSTMENT.PIKEMAN],
    quality: SKILL_QUALITY.S,
    exchangable: false,
    hero: 'h00000065'
  },
  {
    id: 's00000066',
    name: '狼贪枭臣',
    name_en: 'langtanxiaochen',
    desc: '对范围内的敌军共造成120%智力伤害，并驱散其身上的所有增益状态，技能冷却20秒。',
    desc_en: '',
    category: SKILL_CATEGORY.MAIN,
    level: 1,
    status: SKILL_STATUS.UNKNOWN,
    effecient: [SKILL_EFFECIENT.INTELLIGENCE_MULTIPLE, SKILL_EFFECIENT.DEBUFF],
    adjustment: [SKILL_ADJUSTMENT.INFANTRY, SKILL_ADJUSTMENT.ARCHER, SKILL_ADJUSTMENT.CAVALRY, SKILL_ADJUSTMENT.PIKEMAN],
    quality: SKILL_QUALITY.S,
    exchangable: false,
    hero: 'h00000066'
  },
  {
    id: 's00000067',
    name: '龙登南夏',
    name_en: 'longdengnanxia',
    desc: '对范围内的敌军共造成135%智力伤害，并使自身处于免控（免疫所有控制效果），持续10秒，技能冷却20秒。',
    desc_en: '',
    category: SKILL_CATEGORY.MAIN,
    level: 1,
    status: SKILL_STATUS.UNKNOWN,
    effecient: [SKILL_EFFECIENT.INTELLIGENCE_MULTIPLE, SKILL_EFFECIENT.BUFF],
    adjustment: [SKILL_ADJUSTMENT.INFANTRY, SKILL_ADJUSTMENT.ARCHER, SKILL_ADJUSTMENT.CAVALRY, SKILL_ADJUSTMENT.PIKEMAN],
    quality: SKILL_QUALITY.S,
    exchangable: false,
    hero: 'h00000067'
  },
  {
    id: 's00000068',
    name: '引火归原',
    name_en: 'yinhuoguiyuan',
    desc: '（火）对敌方单体武将造成120%智力伤害，并提高自身及1名友方武将20%的破势（无视目标一定比例智力及智力减伤），持续10秒，技能冷却20秒。',
    desc_en: '',
    category: SKILL_CATEGORY.MAIN,
    level: 1,
    status: SKILL_STATUS.UNKNOWN,
    effecient: [SKILL_EFFECIENT.INTELLIGENCE_SINGLE, SKILL_EFFECIENT.BUFF],
    adjustment: [SKILL_ADJUSTMENT.INFANTRY, SKILL_ADJUSTMENT.ARCHER, SKILL_ADJUSTMENT.CAVALRY, SKILL_ADJUSTMENT.PIKEMAN],
    quality: SKILL_QUALITY.S,
    exchangable: false,
    hero: 'h00000068'
  },
  {
    id: 's00000069',
    name: '江东猛虎',
    name_en: 'jiangdongmenghu',
    desc: '对范围内的敌军共造成120%武力伤害，并提高自身100点防御，持续10秒，技能冷却20秒。',
    desc_en: '',
    category: SKILL_CATEGORY.MAIN,
    level: 1,
    status: SKILL_STATUS.UNKNOWN,
    effecient: [SKILL_EFFECIENT.FORCE_MULTIPLE, SKILL_EFFECIENT.BUFF],
    adjustment: [SKILL_ADJUSTMENT.INFANTRY, SKILL_ADJUSTMENT.ARCHER, SKILL_ADJUSTMENT.CAVALRY, SKILL_ADJUSTMENT.PIKEMAN],
    quality: SKILL_QUALITY.S,
    exchangable: false,
    hero: 'h00000069'
  },
  {
    id: 's00000070',
    name: '江上枭姬',
    name_en: 'jiangshangxiaoji',
    desc: '（火）对范围内的敌军共造成120%武力伤害，15%概率对其施加眩晕（无法行动），持续10秒，技能冷却20秒。',
    desc_en: '',
    category: SKILL_CATEGORY.MAIN,
    level: 1,
    status: SKILL_STATUS.UNKNOWN,
    effecient: [SKILL_EFFECIENT.FORCE_MULTIPLE, SKILL_EFFECIENT.CONTROL],
    adjustment: [SKILL_ADJUSTMENT.INFANTRY, SKILL_ADJUSTMENT.ARCHER, SKILL_ADJUSTMENT.CAVALRY, SKILL_ADJUSTMENT.PIKEMAN],
    quality: SKILL_QUALITY.S,
    exchangable: false,
    hero: 'h00000070'
  },
  {
    id: 's00000071',
    name: '雅正之风',
    name_en: 'yazhengzhifeng',
    desc: '（风）对范围内的敌军共造成80%智力伤害并对其施加焚烧（持续火属性智力伤害，总伤害率55%）持续20秒，技能冷却20秒。',
    desc_en: '',
    category: SKILL_CATEGORY.MAIN,
    level: 1,
    status: SKILL_STATUS.UNKNOWN,
    effecient: [SKILL_EFFECIENT.INTELLIGENCE_MULTIPLE],
    adjustment: [SKILL_ADJUSTMENT.INFANTRY, SKILL_ADJUSTMENT.ARCHER, SKILL_ADJUSTMENT.CAVALRY, SKILL_ADJUSTMENT.PIKEMAN],
    quality: SKILL_QUALITY.S,
    exchangable: false,
    hero: 'h00000071'
  },
  {
    id: 's00000072',
    name: '落帆焚舰',
    name_en: 'luofanfenjian',
    desc: '(火)对范围内的敌军共造成120%武力伤害，并提高自身100点防御，持续10秒，技能冷却20秒。',
    desc_en: '',
    category: SKILL_CATEGORY.MAIN,
    level: 1,
    status: SKILL_STATUS.UNKNOWN,
    effecient: [SKILL_EFFECIENT.FORCE_MULTIPLE, SKILL_EFFECIENT.BUFF],
    adjustment: [SKILL_ADJUSTMENT.INFANTRY, SKILL_ADJUSTMENT.ARCHER, SKILL_ADJUSTMENT.CAVALRY, SKILL_ADJUSTMENT.PIKEMAN],
    quality: SKILL_QUALITY.S,
    exchangable: false,
    hero: 'h00000072'
  },
  {
    id: 's00000073',
    name: '霆扫锋猬',
    name_en: 'tingsaofengwei',
    desc: '对敌方单体武将造成95%武力伤害，95%智力伤害，技能冷却20秒。',
    desc_en: '',
    category: SKILL_CATEGORY.MAIN,
    level: 1,
    status: SKILL_STATUS.UNKNOWN,
    effecient: [SKILL_EFFECIENT.FORCE_SINGLE, SKILL_EFFECIENT.INTELLIGENCE_SINGLE],
    adjustment: [SKILL_ADJUSTMENT.INFANTRY, SKILL_ADJUSTMENT.ARCHER, SKILL_ADJUSTMENT.CAVALRY, SKILL_ADJUSTMENT.PIKEMAN],
    quality: SKILL_QUALITY.S,
    exchangable: false,
    hero: 'h00000073'
  },
  {
    id: 's00000074',
    name: '在水一方',
    name_en: 'zaishuiyifang',
    desc: '（水）对范围内的敌军共造成120%智力伤害，如果目标处于水浸，对其施加缴械（无法普通攻击），持续10秒，技能冷却20秒。',
    desc_en: '',
    category: SKILL_CATEGORY.MAIN,
    level: 1,
    status: SKILL_STATUS.UNKNOWN,
    effecient: [SKILL_EFFECIENT.INTELLIGENCE_MULTIPLE, SKILL_EFFECIENT.CONTROL],
    adjustment: [SKILL_ADJUSTMENT.INFANTRY, SKILL_ADJUSTMENT.ARCHER, SKILL_ADJUSTMENT.CAVALRY, SKILL_ADJUSTMENT.PIKEMAN],
    quality: SKILL_QUALITY.S,
    exchangable: false,
    hero: 'h00000074'
  },
  {
    id: 's00000075',
    name: '捭阖之计',
    name_en: 'baihezhiji',
    desc: '对范围内敌军共造成120%智力伤害，并降低其20%智力，持续10秒，技能冷却20秒。',
    desc_en: '',
    category: SKILL_CATEGORY.MAIN,
    level: 1,
    status: SKILL_STATUS.UNKNOWN,
    effecient: [SKILL_EFFECIENT.INTELLIGENCE_MULTIPLE, SKILL_EFFECIENT.DEBUFF],
    adjustment: [SKILL_ADJUSTMENT.INFANTRY, SKILL_ADJUSTMENT.ARCHER, SKILL_ADJUSTMENT.CAVALRY, SKILL_ADJUSTMENT.PIKEMAN],
    quality: SKILL_QUALITY.S,
    exchangable: false,
    hero: 'h00000075'
  },
  {
    id: 's00000076',
    name: '掠阵冲军',
    name_en: 'luezhenchongjun',
    desc: '对范围内的敌军共造成120%武力伤害，50%概率使自身获得1次抵挡（免疫1次主动技能、连击技能伤害），持续10秒，技能冷却20秒。',
    desc_en: '',
    category: SKILL_CATEGORY.MAIN,
    level: 1,
    status: SKILL_STATUS.UNKNOWN,
    effecient: [SKILL_EFFECIENT.FORCE_MULTIPLE, SKILL_EFFECIENT.BUFF],
    adjustment: [SKILL_ADJUSTMENT.INFANTRY, SKILL_ADJUSTMENT.ARCHER, SKILL_ADJUSTMENT.CAVALRY, SKILL_ADJUSTMENT.PIKEMAN],
    quality: SKILL_QUALITY.S,
    exchangable: false,
    hero: 'h00000076'
  },
  {
    id: 's00000077',
    name: '惊涛骇浪',
    name_en: 'jingtaohailang',
    desc: '（水）对范围内的敌军共造成120%武力伤害，并使自身受到伤害降低30%，持续10秒，处于雨天战场时，对攻击目标施加水浸（持续水属性智力伤害，总伤害率25%），持续20秒，技能冷却20秒。',
    desc_en: '',
    category: SKILL_CATEGORY.MAIN,
    level: 1,
    status: SKILL_STATUS.UNKNOWN,
    effecient: [SKILL_EFFECIENT.FORCE_MULTIPLE, SKILL_EFFECIENT.BUFF],
    adjustment: [SKILL_ADJUSTMENT.INFANTRY, SKILL_ADJUSTMENT.ARCHER, SKILL_ADJUSTMENT.CAVALRY, SKILL_ADJUSTMENT.PIKEMAN],
    quality: SKILL_QUALITY.S,
    exchangable: false,
    hero: 'h00000077'
  },
  {
    id: 's00000078',
    name: '烈武争雄',
    name_en: 'liewuzhengxiong',
    desc: '对范围内的敌军共造成120%武力伤害，并提高自身30%武力，持续10秒，技能冷却20秒。',
    desc_en: '',
    category: SKILL_CATEGORY.MAIN,
    level: 1,
    status: SKILL_STATUS.UNKNOWN,
    effecient: [SKILL_EFFECIENT.FORCE_MULTIPLE, SKILL_EFFECIENT.BUFF],
    adjustment: [SKILL_ADJUSTMENT.INFANTRY, SKILL_ADJUSTMENT.ARCHER, SKILL_ADJUSTMENT.CAVALRY, SKILL_ADJUSTMENT.PIKEMAN],
    quality: SKILL_QUALITY.S,
    exchangable: false,
    hero: 'h00000078'
  },
  {
    id: 's00000079',
    name: '刹那芳华',
    name_en: 'chanafanghua',
    desc: '净化（移除目标负面状态）我方全体武将，并对其恢复一定兵力（回复率55%，受智力影响），技能冷却20秒。',
    desc_en: '',
    category: SKILL_CATEGORY.MAIN,
    level: 1,
    status: SKILL_STATUS.UNKNOWN,
    effecient: [SKILL_EFFECIENT.HEAL, SKILL_EFFECIENT.BUFF],
    adjustment: [SKILL_ADJUSTMENT.INFANTRY, SKILL_ADJUSTMENT.ARCHER, SKILL_ADJUSTMENT.CAVALRY, SKILL_ADJUSTMENT.PIKEMAN],
    quality: SKILL_QUALITY.S,
    exchangable: false,
    hero: 'h00000079'
  },
  {
    id: 's00000080',
    name: '克己奉公',
    name_en: 'kejifenggong',
    desc: '为2名友方武将分担40%伤害，且自身受到的分担伤害降低40%，持续20秒，技能冷却20秒。',
    desc_en: '',
    category: SKILL_CATEGORY.MAIN,
    level: 1,
    status: SKILL_STATUS.UNKNOWN,
    effecient: [SKILL_EFFECIENT.PROTECTION],
    adjustment: [SKILL_ADJUSTMENT.INFANTRY, SKILL_ADJUSTMENT.ARCHER, SKILL_ADJUSTMENT.CAVALRY, SKILL_ADJUSTMENT.PIKEMAN],
    quality: SKILL_QUALITY.S,
    exchangable: false,
    hero: 'h00000080'
  },
  {
    id: 's00000081',
    name: '国梁铁脊',
    name_en: 'guoliangtieji',
    desc: '（雷）对范围内的敌军共造成120%武力伤害，并提高1名友方武将30%武力，持续10秒，技能冷却20秒。',
    desc_en: '',
    category: SKILL_CATEGORY.MAIN,
    level: 1,
    status: SKILL_STATUS.UNKNOWN,
    effecient: [SKILL_EFFECIENT.FORCE_MULTIPLE, SKILL_EFFECIENT.BUFF],
    adjustment: [SKILL_ADJUSTMENT.INFANTRY, SKILL_ADJUSTMENT.ARCHER, SKILL_ADJUSTMENT.CAVALRY, SKILL_ADJUSTMENT.PIKEMAN],
    quality: SKILL_QUALITY.S,
    exchangable: false,
    hero: 'h00000081'
  },
  {
    id: 's00000082',
    name: '倾身解烦',
    name_en: 'qingshenjiefan',
    desc: '对范围内的敌军共造成145%武力伤害，此次伤害对骑兵、弓兵武将提高20%，技能冷却20秒。',
    desc_en: '',
    category: SKILL_CATEGORY.MAIN,
    level: 1,
    status: SKILL_STATUS.UNKNOWN,
    effecient: [SKILL_EFFECIENT.FORCE_MULTIPLE],
    adjustment: [SKILL_ADJUSTMENT.INFANTRY, SKILL_ADJUSTMENT.ARCHER, SKILL_ADJUSTMENT.CAVALRY, SKILL_ADJUSTMENT.PIKEMAN],
    quality: SKILL_QUALITY.S,
    exchangable: false,
    hero: 'h00000082'
  },
  {
    id: 's00000083',
    name: '垂诰甘露',
    name_en: 'chuigaoganlu',
    desc: '对范围内的敌军共造成135%智力伤害，技能冷却20秒。',
    desc_en: '',
    category: SKILL_CATEGORY.MAIN,
    level: 1,
    status: SKILL_STATUS.UNKNOWN,
    effecient: [SKILL_EFFECIENT.INTELLIGENCE_MULTIPLE],
    adjustment: [SKILL_ADJUSTMENT.INFANTRY, SKILL_ADJUSTMENT.ARCHER, SKILL_ADJUSTMENT.CAVALRY, SKILL_ADJUSTMENT.PIKEMAN],
    quality: SKILL_QUALITY.A,
    exchangable: false,
    hero: 'h00000083'
  },
  {
    id: 's00000084',
    name: '寒雪奋兵',
    name_en: 'hanxuefenbing',
    desc: '对范围内的敌军共造成135%武力伤害，技能冷却20秒。',
    desc_en: '',
    category: SKILL_CATEGORY.MAIN,
    level: 1,
    status: SKILL_STATUS.UNKNOWN,
    effecient: [SKILL_EFFECIENT.FORCE_MULTIPLE],
    adjustment: [SKILL_ADJUSTMENT.INFANTRY, SKILL_ADJUSTMENT.ARCHER, SKILL_ADJUSTMENT.CAVALRY, SKILL_ADJUSTMENT.PIKEMAN],
    quality: SKILL_QUALITY.A,
    exchangable: false,
    hero: 'h00000084'
  },
  {
    id: 's00000085',
    name: '上兵伐谋',
    name_en: 'shangbingfamou',
    desc: '（雷）对敌方单体武将造成135%智力伤害，技能冷却20秒。',
    desc_en: '',
    category: SKILL_CATEGORY.MAIN,
    level: 1,
    status: SKILL_STATUS.UNKNOWN,
    effecient: [SKILL_EFFECIENT.INTELLIGENCE_SINGLE],
    adjustment: [SKILL_ADJUSTMENT.INFANTRY, SKILL_ADJUSTMENT.ARCHER, SKILL_ADJUSTMENT.CAVALRY, SKILL_ADJUSTMENT.PIKEMAN],
    quality: SKILL_QUALITY.A,
    exchangable: false,
    hero: 'h00000085'
  },
  {
    id: 's00000086',
    name: '踏江破敌',
    name_en: 'tajiangpodi',
    desc: '对范围内的敌军共造成135%武力伤害，技能冷却20秒。',
    desc_en: '',
    category: SKILL_CATEGORY.MAIN,
    level: 1,
    status: SKILL_STATUS.UNKNOWN,
    effecient: [SKILL_EFFECIENT.FORCE_MULTIPLE],
    adjustment: [SKILL_ADJUSTMENT.INFANTRY, SKILL_ADJUSTMENT.ARCHER, SKILL_ADJUSTMENT.CAVALRY, SKILL_ADJUSTMENT.PIKEMAN],
    quality: SKILL_QUALITY.A,
    exchangable: false,
    hero: 'h00000086'
  },
  {
    id: 's00000087',
    name: '铜骨雄风',
    name_en: 'tongguxiongfeng',
    desc: '对自身恢复一定兵力（回复率120%，受防御影响），并提高自身100点防御，持续10秒，技能冷却20秒。',
    desc_en: '',
    category: SKILL_CATEGORY.MAIN,
    level: 1,
    status: SKILL_STATUS.UNKNOWN,
    effecient: [SKILL_EFFECIENT.BUFF, SKILL_EFFECIENT.HEAL],
    adjustment: [SKILL_ADJUSTMENT.INFANTRY, SKILL_ADJUSTMENT.ARCHER, SKILL_ADJUSTMENT.CAVALRY, SKILL_ADJUSTMENT.PIKEMAN],
    quality: SKILL_QUALITY.S,
    exchangable: false,
    hero: 'h00000087'
  },
  {
    id: 's00000088',
    name: '危国宰辅',
    name_en: 'weiguozaifu',
    desc: '对范围内的敌军共造成120%智力伤害，并提高自身50点智力、攻速，持续10秒，技能冷却20秒。',
    desc_en: '',
    category: SKILL_CATEGORY.MAIN,
    level: 1,
    status: SKILL_STATUS.UNKNOWN,
    effecient: [SKILL_EFFECIENT.INTELLIGENCE_MULTIPLE, SKILL_EFFECIENT.BUFF],
    adjustment: [SKILL_ADJUSTMENT.INFANTRY, SKILL_ADJUSTMENT.ARCHER, SKILL_ADJUSTMENT.CAVALRY, SKILL_ADJUSTMENT.PIKEMAN],
    quality: SKILL_QUALITY.S,
    exchangable: false,
    hero: 'h00000088'
  },
  {
    id: 's00000089',
    name: '无冕之后',
    name_en: 'wumianzhihou',
    desc: '对范围内的敌军共造成120%智力伤害，并提高我方全体女性武将50点魅力，持续10秒，技能冷却20秒。',
    desc_en: '',
    category: SKILL_CATEGORY.MAIN,
    level: 1,
    status: SKILL_STATUS.UNKNOWN,
    effecient: [SKILL_EFFECIENT.INTELLIGENCE_MULTIPLE, SKILL_EFFECIENT.BUFF],
    adjustment: [SKILL_ADJUSTMENT.INFANTRY, SKILL_ADJUSTMENT.ARCHER, SKILL_ADJUSTMENT.CAVALRY, SKILL_ADJUSTMENT.PIKEMAN],
    quality: SKILL_QUALITY.S,
    exchangable: false,
    hero: 'h00000089'
  },
  {
    id: 's00000090',
    name: '雄豪安东',
    name_en: 'xionghaoandong',
    desc: '对自身恢复一定兵力（回复率120%，受防御影响），并提高自身50点防御、智力，持续10秒，技能冷却20秒。',
    desc_en: '',
    category: SKILL_CATEGORY.MAIN,
    level: 1,
    status: SKILL_STATUS.UNKNOWN,
    effecient: [SKILL_EFFECIENT.HEAL, SKILL_EFFECIENT.BUFF],
    adjustment: [SKILL_ADJUSTMENT.INFANTRY, SKILL_ADJUSTMENT.ARCHER, SKILL_ADJUSTMENT.CAVALRY, SKILL_ADJUSTMENT.PIKEMAN],
    quality: SKILL_QUALITY.S,
    exchangable: false,
    hero: 'h00000090'
  },
  {
    id: 's00000091',
    name: '鬼泣神号',
    name_en: 'guiqishenhao',
    desc: '对范围内的敌军共造成120%武力伤害，并降低其武力伤害20%，持续10秒，技能冷却20秒。',
    desc_en: '',
    category: SKILL_CATEGORY.MAIN,
    level: 1,
    status: SKILL_STATUS.UNKNOWN,
    effecient: [SKILL_EFFECIENT.FORCE_MULTIPLE, SKILL_EFFECIENT.DEBUFF],
    adjustment: [SKILL_ADJUSTMENT.INFANTRY, SKILL_ADJUSTMENT.ARCHER, SKILL_ADJUSTMENT.CAVALRY, SKILL_ADJUSTMENT.PIKEMAN],
    quality: SKILL_QUALITY.S,
    exchangable: false,
    hero: 'h00000091'
  },
  {
    id: 's00000092',
    name: '豺戾当涂',
    name_en: 'chailidangtu',
    desc: '对范围内的敌军共造成130%武力伤害，本次伤害获得50%励军（基于造成的武力伤害回复一定兵力），技能冷却20秒。',
    desc_en: '',
    category: SKILL_CATEGORY.MAIN,
    level: 1,
    status: SKILL_STATUS.UNKNOWN,
    effecient: [SKILL_EFFECIENT.FORCE_MULTIPLE, SKILL_EFFECIENT.HEAL],
    adjustment: [SKILL_ADJUSTMENT.INFANTRY, SKILL_ADJUSTMENT.ARCHER, SKILL_ADJUSTMENT.CAVALRY, SKILL_ADJUSTMENT.PIKEMAN],
    quality: SKILL_QUALITY.S,
    exchangable: false,
    hero: 'h00000092'
  },
  {
    id: 's00000093',
    name: '闭月',
    name_en: 'biyue',
    desc: '对范围内的敌军共造成120%智力伤害，并降低其20%防御，持续10秒，技能冷却20秒。',
    desc_en: '',
    category: SKILL_CATEGORY.MAIN,
    level: 1,
    status: SKILL_STATUS.UNKNOWN,
    effecient: [SKILL_EFFECIENT.INTELLIGENCE_MULTIPLE, SKILL_EFFECIENT.DEBUFF],
    adjustment: [SKILL_ADJUSTMENT.INFANTRY, SKILL_ADJUSTMENT.ARCHER, SKILL_ADJUSTMENT.CAVALRY, SKILL_ADJUSTMENT.PIKEMAN],
    quality: SKILL_QUALITY.S,
    exchangable: false,
    hero: 'h00000093'
  },
  {
    id: 's00000094',
    name: '末裔火神',
    name_en: 'moyihuoshen',
    desc: '对范围内的敌军共造成120%武力伤害，并提高自身30%普攻伤害，持续10秒，技能冷却20秒。',
    desc_en: '',
    category: SKILL_CATEGORY.MAIN,
    level: 1,
    status: SKILL_STATUS.UNKNOWN,
    effecient: [SKILL_EFFECIENT.FORCE_MULTIPLE, SKILL_EFFECIENT.BUFF],
    adjustment: [SKILL_ADJUSTMENT.INFANTRY, SKILL_ADJUSTMENT.ARCHER, SKILL_ADJUSTMENT.CAVALRY, SKILL_ADJUSTMENT.PIKEMAN],
    quality: SKILL_QUALITY.S,
    exchangable: false,
    hero: 'h00000094'
  },
  {
    id: 's00000095',
    name: '黄天为棋',
    name_en: 'huangtianweiqi',
    desc: '（雷）对范围内的敌军共造成120%智力伤害，并使其受到智力伤害提高20%，持续10秒，技能冷却20秒。',
    desc_en: '',
    category: SKILL_CATEGORY.MAIN,
    level: 1,
    status: SKILL_STATUS.UNKNOWN,
    effecient: [SKILL_EFFECIENT.INTELLIGENCE_MULTIPLE, SKILL_EFFECIENT.DEBUFF],
    adjustment: [SKILL_ADJUSTMENT.INFANTRY, SKILL_ADJUSTMENT.ARCHER, SKILL_ADJUSTMENT.CAVALRY, SKILL_ADJUSTMENT.PIKEMAN],
    quality: SKILL_QUALITY.S,
    exchangable: false,
    hero: 'h00000095'
  },
  {
    id: 's00000096',
    name: '悬壶济世',
    name_en: 'xuanhujishi',
    desc: '对2名友方武将施加恢复状态（持续回复兵力，总回复率85%，受智力影响），并使其受到连击技能伤害降低40%，持续10秒，技能冷却20秒。',
    desc_en: '',
    category: SKILL_CATEGORY.MAIN,
    level: 1,
    status: SKILL_STATUS.UNKNOWN,
    effecient: [SKILL_EFFECIENT.HEAL, SKILL_EFFECIENT.BUFF],
    adjustment: [SKILL_ADJUSTMENT.INFANTRY, SKILL_ADJUSTMENT.ARCHER, SKILL_ADJUSTMENT.CAVALRY, SKILL_ADJUSTMENT.PIKEMAN],
    quality: SKILL_QUALITY.S,
    exchangable: false,
    hero: 'h00000096'
  },
  {
    id: 's00000097',
    name: '厌蛊制胜',
    name_en: 'yanguzhisheng',
    desc: '对范围内的敌方武将共造成120%智力伤害，并降低其50点智力，持续10秒，技能冷却20秒。',
    desc_en: '',
    category: SKILL_CATEGORY.MAIN,
    level: 1,
    status: SKILL_STATUS.UNKNOWN,
    effecient: [SKILL_EFFECIENT.INTELLIGENCE_MULTIPLE, SKILL_EFFECIENT.DEBUFF],
    adjustment: [SKILL_ADJUSTMENT.INFANTRY, SKILL_ADJUSTMENT.ARCHER, SKILL_ADJUSTMENT.CAVALRY, SKILL_ADJUSTMENT.PIKEMAN],
    quality: SKILL_QUALITY.S,
    exchangable: false,
    hero: 'h00000097'
  },
  {
    id: 's00000098',
    name: '横刀紫廷',
    name_en: 'hengdaoziting',
    desc: '对范围内的敌军共造成80%智力伤害，并对其施加水浸（持续水属性智力伤害，总伤害率55%），持续20秒，技能冷却20秒。',
    desc_en: '',
    category: SKILL_CATEGORY.MAIN,
    level: 1,
    status: SKILL_STATUS.UNKNOWN,
    effecient: [SKILL_EFFECIENT.INTELLIGENCE_MULTIPLE],
    adjustment: [SKILL_ADJUSTMENT.INFANTRY, SKILL_ADJUSTMENT.ARCHER, SKILL_ADJUSTMENT.CAVALRY, SKILL_ADJUSTMENT.PIKEMAN],
    quality: SKILL_QUALITY.S,
    exchangable: false,
    hero: 'h00000098'
  },
  {
    id: 's00000099',
    name: '南中魁首',
    name_en: 'nanzhongkuishou',
    desc: '对范围内的敌军共造成120%武力伤害，25%概率对其施加力竭（无法造成伤害），持续10秒，技能冷却20秒。',
    desc_en: '',
    category: SKILL_CATEGORY.MAIN,
    level: 1,
    status: SKILL_STATUS.UNKNOWN,
    effecient: [SKILL_EFFECIENT.FORCE_MULTIPLE, SKILL_EFFECIENT.CONTROL],
    adjustment: [SKILL_ADJUSTMENT.INFANTRY, SKILL_ADJUSTMENT.ARCHER, SKILL_ADJUSTMENT.CAVALRY, SKILL_ADJUSTMENT.PIKEMAN],
    quality: SKILL_QUALITY.S,
    exchangable: false,
    hero: 'h00000099'
  },
  {
    id: 's00000100',
    name: '胡笳归赋',
    name_en: 'hujiaguifu',
    desc: '对2名友方武将恢复一定兵力（回复率90%，受智力影响），技能冷却20秒。',
    desc_en: '',
    category: SKILL_CATEGORY.MAIN,
    level: 1,
    status: SKILL_STATUS.UNKNOWN,
    effecient: [SKILL_EFFECIENT.HEAL],
    adjustment: [SKILL_ADJUSTMENT.INFANTRY, SKILL_ADJUSTMENT.ARCHER, SKILL_ADJUSTMENT.CAVALRY, SKILL_ADJUSTMENT.PIKEMAN],
    quality: SKILL_QUALITY.S,
    exchangable: false,
    hero: 'h00000100'
  },
  {
    id: 's00000101',
    name: '步斗踏罡',
    name_en: 'budoutagang',
    desc: '对范围内的敌军共造成120%智力伤害，并驱散其身上的所有增益状态，技能冷却20秒。',
    desc_en: '',
    category: SKILL_CATEGORY.MAIN,
    level: 1,
    status: SKILL_STATUS.UNKNOWN,
    effecient: [SKILL_EFFECIENT.INTELLIGENCE_MULTIPLE, SKILL_EFFECIENT.DEBUFF],
    adjustment: [SKILL_ADJUSTMENT.INFANTRY, SKILL_ADJUSTMENT.ARCHER, SKILL_ADJUSTMENT.CAVALRY, SKILL_ADJUSTMENT.PIKEMAN],
    quality: SKILL_QUALITY.S,
    exchangable: false,
    hero: 'h00000101'
  },
  {
    id: 's00000102',
    name: '神威上将',
    name_en: 'shenweishangjiang',
    desc: '对范围内的敌军共造成135%武力伤害，技能冷却20秒。',
    desc_en: '',
    category: SKILL_CATEGORY.MAIN,
    level: 1,
    status: SKILL_STATUS.UNKNOWN,
    effecient: [SKILL_EFFECIENT.FORCE_MULTIPLE],
    adjustment: [SKILL_ADJUSTMENT.INFANTRY, SKILL_ADJUSTMENT.ARCHER, SKILL_ADJUSTMENT.CAVALRY, SKILL_ADJUSTMENT.PIKEMAN],
    quality: SKILL_QUALITY.A,
    exchangable: false,
    hero: 'h00000102'
  },
  {
    id: 's00000103',
    name: '肇祸乱戚',
    name_en: 'zhaohuoluanqi',
    desc: '（火）对范围内的敌军共造成135%智力伤害，技能冷却20秒。',
    desc_en: '',
    category: SKILL_CATEGORY.MAIN,
    level: 1,
    status: SKILL_STATUS.UNKNOWN,
    effecient: [SKILL_EFFECIENT.INTELLIGENCE_MULTIPLE],
    adjustment: [SKILL_ADJUSTMENT.INFANTRY, SKILL_ADJUSTMENT.ARCHER, SKILL_ADJUSTMENT.CAVALRY, SKILL_ADJUSTMENT.PIKEMAN],
    quality: SKILL_QUALITY.A,
    exchangable: false,
    hero: 'h00000103'
  },
  {
    id: 's00000104',
    name: '魂引四泉',
    name_en: 'hunyinsiquan',
    desc: '对范围内的敌军共造成135%智力伤害，技能冷却20秒。',
    desc_en: '',
    category: SKILL_CATEGORY.MAIN,
    level: 1,
    status: SKILL_STATUS.UNKNOWN,
    effecient: [SKILL_EFFECIENT.INTELLIGENCE_MULTIPLE],
    adjustment: [SKILL_ADJUSTMENT.INFANTRY, SKILL_ADJUSTMENT.ARCHER, SKILL_ADJUSTMENT.CAVALRY, SKILL_ADJUSTMENT.PIKEMAN],
    quality: SKILL_QUALITY.A,
    exchangable: false,
    hero: 'h00000104'
  },
  {
    id: 's00000105',
    name: '毒策',
    name_en: 'duce',
    desc: '（毒）对范围内的敌军共造成135%智力伤害，技能冷却20秒。',
    desc_en: '',
    category: SKILL_CATEGORY.MAIN,
    level: 1,
    status: SKILL_STATUS.UNKNOWN,
    effecient: [SKILL_EFFECIENT.INTELLIGENCE_MULTIPLE],
    adjustment: [SKILL_ADJUSTMENT.INFANTRY, SKILL_ADJUSTMENT.ARCHER, SKILL_ADJUSTMENT.CAVALRY, SKILL_ADJUSTMENT.PIKEMAN],
    quality: SKILL_QUALITY.A,
    exchangable: false,
    hero: 'h00000105'
  },
  {
    id: 's00000106',
    name: '人公将军',
    name_en: 'rengongjiangjun',
    desc: '（雷）对范围内的敌军共造成135%武力伤害，技能冷却20秒。',
    desc_en: '',
    category: SKILL_CATEGORY.MAIN,
    level: 1,
    status: SKILL_STATUS.UNKNOWN,
    effecient: [SKILL_EFFECIENT.FORCE_MULTIPLE],
    adjustment: [SKILL_ADJUSTMENT.INFANTRY, SKILL_ADJUSTMENT.ARCHER, SKILL_ADJUSTMENT.CAVALRY, SKILL_ADJUSTMENT.PIKEMAN],
    quality: SKILL_QUALITY.A,
    exchangable: false,
    hero: 'h00000106'
  },
  {
    id: 's00000107',
    name: '摧坚获丑',
    name_en: 'cuijianhuochou',
    desc: '对范围内的敌军共造成135%武力伤害，技能冷却20秒。',
    desc_en: '',
    category: SKILL_CATEGORY.MAIN,
    level: 1,
    status: SKILL_STATUS.UNKNOWN,
    effecient: [SKILL_EFFECIENT.FORCE_MULTIPLE],
    adjustment: [SKILL_ADJUSTMENT.INFANTRY, SKILL_ADJUSTMENT.ARCHER, SKILL_ADJUSTMENT.CAVALRY, SKILL_ADJUSTMENT.PIKEMAN],
    quality: SKILL_QUALITY.A,
    exchangable: false,
    hero: 'h00000107'
  },
  {
    id: 's00000108',
    name: '暴虎冯河',
    name_en: 'baohupinghe',
    desc: '对范围内的敌军共造成135%武力伤害，技能冷却20秒。',
    desc_en: '',
    category: SKILL_CATEGORY.MAIN,
    level: 1,
    status: SKILL_STATUS.UNKNOWN,
    effecient: [SKILL_EFFECIENT.FORCE_MULTIPLE],
    adjustment: [SKILL_ADJUSTMENT.INFANTRY, SKILL_ADJUSTMENT.ARCHER, SKILL_ADJUSTMENT.CAVALRY, SKILL_ADJUSTMENT.PIKEMAN],
    quality: SKILL_QUALITY.A,
    exchangable: false,
    hero: 'h00000108'
  },
  {
    id: 's00000109',
    name: '宗戚风望',
    name_en: 'zongqifengwang',
    desc: '（风）对范围内的敌军共造成135%智力伤害，技能冷却20秒。',
    desc_en: '',
    category: SKILL_CATEGORY.MAIN,
    level: 1,
    status: SKILL_STATUS.UNKNOWN,
    effecient: [SKILL_EFFECIENT.INTELLIGENCE_MULTIPLE],
    adjustment: [SKILL_ADJUSTMENT.INFANTRY, SKILL_ADJUSTMENT.ARCHER, SKILL_ADJUSTMENT.CAVALRY, SKILL_ADJUSTMENT.PIKEMAN],
    quality: SKILL_QUALITY.A,
    exchangable: false,
    hero: 'h00000109'
  },
  {
    id: 's00000110',
    name: '湖海豪气',
    name_en: 'huhaihaoqi',
    desc: '对范围内的敌军共造成135%智力伤害，技能冷却20秒。',
    desc_en: '',
    category: SKILL_CATEGORY.MAIN,
    level: 1,
    status: SKILL_STATUS.UNKNOWN,
    effecient: [SKILL_EFFECIENT.INTELLIGENCE_MULTIPLE],
    adjustment: [SKILL_ADJUSTMENT.INFANTRY, SKILL_ADJUSTMENT.ARCHER, SKILL_ADJUSTMENT.CAVALRY, SKILL_ADJUSTMENT.PIKEMAN],
    quality: SKILL_QUALITY.A,
    exchangable: false,
    hero: 'h00000110'
  },
  {
    id: 's00000111',
    name: '矜武斩将',
    name_en: 'jinwuzhanjiang',
    desc: '对范围内的敌军共造成135%武力伤害，技能冷却20秒。',
    desc_en: '',
    category: SKILL_CATEGORY.MAIN,
    level: 1,
    status: SKILL_STATUS.UNKNOWN,
    effecient: [SKILL_EFFECIENT.FORCE_MULTIPLE],
    adjustment: [SKILL_ADJUSTMENT.INFANTRY, SKILL_ADJUSTMENT.ARCHER, SKILL_ADJUSTMENT.CAVALRY, SKILL_ADJUSTMENT.PIKEMAN],
    quality: SKILL_QUALITY.A,
    exchangable: false,
    hero: 'h00000111'
  },
  {
    id: 's00000112',
    name: '凶兵结祸',
    name_en: 'xiongbingjiehuo',
    desc: '对范围内的敌军共造成135%武力伤害，技能冷却20秒。',
    desc_en: '',
    category: SKILL_CATEGORY.MAIN,
    level: 1,
    status: SKILL_STATUS.UNKNOWN,
    effecient: [SKILL_EFFECIENT.FORCE_MULTIPLE],
    adjustment: [SKILL_ADJUSTMENT.INFANTRY, SKILL_ADJUSTMENT.ARCHER, SKILL_ADJUSTMENT.CAVALRY, SKILL_ADJUSTMENT.PIKEMAN],
    quality: SKILL_QUALITY.A,
    exchangable: false,
    hero: 'h00000112'
  },
  {
    id: 's00000113',
    name: '盘马横戈',
    name_en: 'panmahengge',
    desc: '对范围内的敌军共造成135%武力伤害，技能冷却20秒。',
    desc_en: '',
    category: SKILL_CATEGORY.MAIN,
    level: 1,
    status: SKILL_STATUS.UNKNOWN,
    effecient: [SKILL_EFFECIENT.FORCE_MULTIPLE],
    adjustment: [SKILL_ADJUSTMENT.INFANTRY, SKILL_ADJUSTMENT.ARCHER, SKILL_ADJUSTMENT.CAVALRY, SKILL_ADJUSTMENT.PIKEMAN],
    quality: SKILL_QUALITY.A,
    exchangable: false,
    hero: 'h00000113'
  },
  {
    id: 's00000114',
    name: '符玺僭位',
    name_en: 'fuxijianwei',
    desc: '对范围内的敌军共造成135%智力伤害，技能冷却20秒。',
    desc_en: '',
    category: SKILL_CATEGORY.MAIN,
    level: 1,
    status: SKILL_STATUS.UNKNOWN,
    effecient: [SKILL_EFFECIENT.INTELLIGENCE_MULTIPLE],
    adjustment: [SKILL_ADJUSTMENT.INFANTRY, SKILL_ADJUSTMENT.ARCHER, SKILL_ADJUSTMENT.CAVALRY, SKILL_ADJUSTMENT.PIKEMAN],
    quality: SKILL_QUALITY.A,
    exchangable: false,
    hero: 'h00000114'
  },
  {
    id: 's00000115',
    name: '地公将军',
    name_en: 'digongjiangjun',
    desc: '对范围内的敌军共造成135%智力伤害，技能冷却20秒。',
    desc_en: '',
    category: SKILL_CATEGORY.MAIN,
    level: 1,
    status: SKILL_STATUS.UNKNOWN,
    effecient: [SKILL_EFFECIENT.INTELLIGENCE_MULTIPLE],
    adjustment: [SKILL_ADJUSTMENT.INFANTRY, SKILL_ADJUSTMENT.ARCHER, SKILL_ADJUSTMENT.CAVALRY, SKILL_ADJUSTMENT.PIKEMAN],
    quality: SKILL_QUALITY.A,
    exchangable: false,
    hero: 'h00000115'
  },
  {
    id: 's00000116',
    name: '临锋制敌',
    name_en: 'linfengzhidi',
    desc: '对范围内的敌军共造成135%武力伤害，技能冷却20秒。',
    desc_en: '',
    category: SKILL_CATEGORY.MAIN,
    level: 1,
    status: SKILL_STATUS.UNKNOWN,
    effecient: [SKILL_EFFECIENT.FORCE_MULTIPLE],
    adjustment: [SKILL_ADJUSTMENT.INFANTRY, SKILL_ADJUSTMENT.ARCHER, SKILL_ADJUSTMENT.CAVALRY, SKILL_ADJUSTMENT.PIKEMAN],
    quality: SKILL_QUALITY.A,
    exchangable: false,
    hero: 'h00000116'
  },
  {
    id: 's00000117',
    name: '弭乱图过',
    name_en: 'miluantuguo',
    desc: '对范围内的敌军共造成135%武力伤害，技能冷却20秒。',
    desc_en: '',
    category: SKILL_CATEGORY.MAIN,
    level: 1,
    status: SKILL_STATUS.UNKNOWN,
    effecient: [SKILL_EFFECIENT.FORCE_MULTIPLE],
    adjustment: [SKILL_ADJUSTMENT.INFANTRY, SKILL_ADJUSTMENT.ARCHER, SKILL_ADJUSTMENT.CAVALRY, SKILL_ADJUSTMENT.PIKEMAN],
    quality: SKILL_QUALITY.A,
    exchangable: false,
    hero: 'h00000117'
  },
  {
    id: 's00000118',
    name: '暗箭伤人',
    name_en: 'anjianshangren',
    desc: '对范围内的敌军共造成135%武力伤害，技能冷却20秒。',
    desc_en: '',
    category: SKILL_CATEGORY.MAIN,
    level: 1,
    status: SKILL_STATUS.UNKNOWN,
    effecient: [SKILL_EFFECIENT.FORCE_MULTIPLE],
    adjustment: [SKILL_ADJUSTMENT.INFANTRY, SKILL_ADJUSTMENT.ARCHER, SKILL_ADJUSTMENT.CAVALRY, SKILL_ADJUSTMENT.PIKEMAN],
    quality: SKILL_QUALITY.A,
    exchangable: false,
    hero: 'h00000118'
  },
  {
    id: 's00000119',
    name: '蓄谋讨佞',
    name_en: 'xumoutaoning',
    desc: '（风）对范围内的敌军共造成135%智力伤害，技能冷却20秒。',
    desc_en: '',
    category: SKILL_CATEGORY.MAIN,
    level: 1,
    status: SKILL_STATUS.UNKNOWN,
    effecient: [SKILL_EFFECIENT.INTELLIGENCE_MULTIPLE],
    adjustment: [SKILL_ADJUSTMENT.INFANTRY, SKILL_ADJUSTMENT.ARCHER, SKILL_ADJUSTMENT.CAVALRY, SKILL_ADJUSTMENT.PIKEMAN],
    quality: SKILL_QUALITY.A,
    exchangable: false,
    hero: 'h00000119'
  },
  {
    id: 's00000120',
    name: '乌戈悍主',
    name_en: 'wugehanzhu',
    desc: '对范围内的敌军共造成135%武力伤害，技能冷却20秒。',
    desc_en: '',
    category: SKILL_CATEGORY.MAIN,
    level: 1,
    status: SKILL_STATUS.UNKNOWN,
    effecient: [SKILL_EFFECIENT.FORCE_MULTIPLE],
    adjustment: [SKILL_ADJUSTMENT.INFANTRY, SKILL_ADJUSTMENT.ARCHER, SKILL_ADJUSTMENT.CAVALRY, SKILL_ADJUSTMENT.PIKEMAN],
    quality: SKILL_QUALITY.A,
    exchangable: false,
    hero: 'h00000120'
  },
  {
    id: 's00000121',
    name: '鸿图昭武',
    name_en: 'hongtuzhaowu',
    desc: '对范围内的敌军共造成70%武力伤害，并对其施加溃散（持续武力伤害，总伤害率47.5%），持续20秒，技能冷却20秒。',
    desc_en: '',
    category: SKILL_CATEGORY.MAIN,
    level: 1,
    status: SKILL_STATUS.UNKNOWN,
    effecient: [SKILL_EFFECIENT.FORCE_MULTIPLE],
    adjustment: [SKILL_ADJUSTMENT.INFANTRY, SKILL_ADJUSTMENT.ARCHER, SKILL_ADJUSTMENT.CAVALRY, SKILL_ADJUSTMENT.PIKEMAN],
    quality: SKILL_QUALITY.A,
    exchangable: false,
    hero: 'h00000121'
  },
  {
    id: 's00000122',
    name: '安危定倾',
    name_en: 'anweidingqing',
    desc: '对范围内的敌军共造成135%武力伤害，技能冷却20秒。',
    desc_en: '',
    category: SKILL_CATEGORY.MAIN,
    level: 1,
    status: SKILL_STATUS.UNKNOWN,
    effecient: [SKILL_EFFECIENT.FORCE_MULTIPLE],
    adjustment: [SKILL_ADJUSTMENT.INFANTRY, SKILL_ADJUSTMENT.ARCHER, SKILL_ADJUSTMENT.CAVALRY, SKILL_ADJUSTMENT.PIKEMAN],
    quality: SKILL_QUALITY.A,
    exchangable: false,
    hero: 'h00000122'
  },
  {
    id: 's00000123',
    name: '射枭汴水',
    name_en: 'shexiaobianshui',
    desc: '对范围内的敌军共造成135%武力伤害，技能冷却20秒。',
    desc_en: '',
    category: SKILL_CATEGORY.MAIN,
    level: 1,
    status: SKILL_STATUS.UNKNOWN,
    effecient: [SKILL_EFFECIENT.FORCE_MULTIPLE],
    adjustment: [SKILL_ADJUSTMENT.INFANTRY, SKILL_ADJUSTMENT.ARCHER, SKILL_ADJUSTMENT.CAVALRY, SKILL_ADJUSTMENT.PIKEMAN],
    quality: SKILL_QUALITY.A,
    exchangable: false,
    hero: 'h00000123'
  },
  {
    id: 's00000124',
    name: '抚境维城',
    name_en: 'fujingweicheng',
    desc: '对范围内的敌军共造成135%智力伤害，技能冷却20秒。',
    desc_en: '',
    category: SKILL_CATEGORY.MAIN,
    level: 1,
    status: SKILL_STATUS.UNKNOWN,
    effecient: [SKILL_EFFECIENT.INTELLIGENCE_MULTIPLE],
    adjustment: [SKILL_ADJUSTMENT.INFANTRY, SKILL_ADJUSTMENT.ARCHER, SKILL_ADJUSTMENT.CAVALRY, SKILL_ADJUSTMENT.PIKEMAN],
    quality: SKILL_QUALITY.A,
    exchangable: false,
    hero: 'h00000124'
  },
  {
    id: 's00000125',
    name: '平乱镇国',
    name_en: 'pingluanzhenguo',
    desc: '对范围内的敌军共造成135%武力伤害，技能冷却20秒。',
    desc_en: '',
    category: SKILL_CATEGORY.MAIN,
    level: 1,
    status: SKILL_STATUS.UNKNOWN,
    effecient: [SKILL_EFFECIENT.FORCE_MULTIPLE],
    adjustment: [SKILL_ADJUSTMENT.INFANTRY, SKILL_ADJUSTMENT.ARCHER, SKILL_ADJUSTMENT.CAVALRY, SKILL_ADJUSTMENT.PIKEMAN],
    quality: SKILL_QUALITY.A,
    exchangable: false,
    hero: 'h00000125'
  },
  {
    id: 's00000126',
    name: '蛮犷逞威',
    name_en: 'manguangchengwei',
    desc: '对范围内的敌军共造成135%武力伤害，技能冷却20秒。',
    desc_en: '',
    category: SKILL_CATEGORY.MAIN,
    level: 1,
    status: SKILL_STATUS.UNKNOWN,
    effecient: [SKILL_EFFECIENT.FORCE_MULTIPLE],
    adjustment: [SKILL_ADJUSTMENT.INFANTRY, SKILL_ADJUSTMENT.ARCHER, SKILL_ADJUSTMENT.CAVALRY, SKILL_ADJUSTMENT.PIKEMAN],
    quality: SKILL_QUALITY.A,
    exchangable: false,
    hero: 'h00000126'
  },
  {
    id: 's00000127',
    name: '朔北天骄',
    name_en: 'shuobeitianjiao',
    desc: '对范围内的敌军共造成120%武力伤害，并使我方骑兵受到伤害降低20%，持续10秒，技能冷却20秒。',
    desc_en: '',
    category: SKILL_CATEGORY.MAIN,
    level: 1,
    status: SKILL_STATUS.UNKNOWN,
    effecient: [SKILL_EFFECIENT.FORCE_MULTIPLE, SKILL_EFFECIENT.BUFF],
    adjustment: [SKILL_ADJUSTMENT.INFANTRY, SKILL_ADJUSTMENT.ARCHER, SKILL_ADJUSTMENT.CAVALRY, SKILL_ADJUSTMENT.PIKEMAN],
    quality: SKILL_QUALITY.S,
    exchangable: false,
    hero: 'h00000127'
  },
  {
    id: 's00000128',
    name: '驱虏关山',
    name_en: 'quluguanshan',
    desc: '对范围内的敌军共造成120%武力伤害，并提高我方全体骑兵武将20%武力伤害，持续10秒，技能冷却20秒。',
    desc_en: '',
    category: SKILL_CATEGORY.MAIN,
    level: 1,
    status: SKILL_STATUS.UNKNOWN,
    effecient: [SKILL_EFFECIENT.FORCE_MULTIPLE, SKILL_EFFECIENT.BUFF],
    adjustment: [SKILL_ADJUSTMENT.INFANTRY, SKILL_ADJUSTMENT.ARCHER, SKILL_ADJUSTMENT.CAVALRY, SKILL_ADJUSTMENT.PIKEMAN],
    quality: SKILL_QUALITY.S,
    exchangable: false,
    hero: 'h00000128'
  },
  {
    id: 's00000129',
    name: '守正出奇',
    name_en: 'shouzhengchuqi',
    desc: '对范围内的敌军共造成120%智力伤害，并使其受到智力伤害提高20%，持续10秒，技能冷却20秒。',
    desc_en: '',
    category: SKILL_CATEGORY.MAIN,
    level: 1,
    status: SKILL_STATUS.UNKNOWN,
    effecient: [SKILL_EFFECIENT.INTELLIGENCE_MULTIPLE, SKILL_EFFECIENT.DEBUFF],
    adjustment: [SKILL_ADJUSTMENT.INFANTRY, SKILL_ADJUSTMENT.ARCHER, SKILL_ADJUSTMENT.CAVALRY, SKILL_ADJUSTMENT.PIKEMAN],
    quality: SKILL_QUALITY.S,
    exchangable: false,
    hero: 'h00000129'
  },
  {
    id: 's00000130',
    name: '硕彦鸿儒',
    name_en: 'shuoyanhongru',
    desc: '对范围内的敌军共造成120%智力伤害，并提高我方群势力武将10%全属性（武力、智力、防御和攻速），持续10秒，技能冷却20秒。',
    desc_en: '',
    category: SKILL_CATEGORY.MAIN,
    level: 1,
    status: SKILL_STATUS.UNKNOWN,
    effecient: [SKILL_EFFECIENT.INTELLIGENCE_MULTIPLE, SKILL_EFFECIENT.BUFF],
    adjustment: [SKILL_ADJUSTMENT.INFANTRY, SKILL_ADJUSTMENT.ARCHER, SKILL_ADJUSTMENT.CAVALRY, SKILL_ADJUSTMENT.PIKEMAN],
    quality: SKILL_QUALITY.S,
    exchangable: false,
    hero: 'h00000130'
  },
  {
    id: 's00000131',
    name: '荡析克乱',
    name_en: 'dangxikeluan',
    desc: '对范围内的敌军共造成120%武力伤害，并降低其50点武力，持续10秒，技能冷却20秒。',
    desc_en: '',
    category: SKILL_CATEGORY.MAIN,
    level: 1,
    status: SKILL_STATUS.UNKNOWN,
    effecient: [SKILL_EFFECIENT.FORCE_MULTIPLE, SKILL_EFFECIENT.DEBUFF],
    adjustment: [SKILL_ADJUSTMENT.INFANTRY, SKILL_ADJUSTMENT.ARCHER, SKILL_ADJUSTMENT.CAVALRY, SKILL_ADJUSTMENT.PIKEMAN],
    quality: SKILL_QUALITY.S,
    exchangable: false,
    hero: 'h00000131'
  },
  {
    id: 's00000132',
    name: '黑山盗首',
    name_en: 'heishandaoshou',
    desc: '对范围内的敌军共造成120%武力伤害，并提高自身30%武力伤害，持续10秒，技能冷却20秒。',
    desc_en: '',
    category: SKILL_CATEGORY.MAIN,
    level: 1,
    status: SKILL_STATUS.UNKNOWN,
    effecient: [SKILL_EFFECIENT.FORCE_MULTIPLE, SKILL_EFFECIENT.BUFF],
    adjustment: [SKILL_ADJUSTMENT.INFANTRY, SKILL_ADJUSTMENT.ARCHER, SKILL_ADJUSTMENT.CAVALRY, SKILL_ADJUSTMENT.PIKEMAN],
    quality: SKILL_QUALITY.S,
    exchangable: false,
    hero: 'h00000132'
  },
  {
    id: 's00000133',
    name: '无上将军',
    name_en: 'wushangjiangjun',
    desc: '提高2名友方上将40%伤害，持续10秒，技能冷却20秒。',
    desc_en: '',
    category: SKILL_CATEGORY.MAIN,
    level: 1,
    status: SKILL_STATUS.UNKNOWN,
    effecient: [SKILL_EFFECIENT.BUFF],
    adjustment: [SKILL_ADJUSTMENT.INFANTRY, SKILL_ADJUSTMENT.ARCHER, SKILL_ADJUSTMENT.CAVALRY, SKILL_ADJUSTMENT.PIKEMAN],
    quality: SKILL_QUALITY.S,
    exchangable: false,
    hero: 'h00000133'
  },
  {
    id: 's00000134',
    name: '太平圣姑',
    name_en: 'taipingshenggu',
    desc: '（雷）对范围内的敌军共造成120%智力伤害，并使其受到雷属性伤害提高30%，持续10秒，技能冷却20秒。',
    desc_en: '',
    category: SKILL_CATEGORY.MAIN,
    level: 1,
    status: SKILL_STATUS.UNKNOWN,
    effecient: [SKILL_EFFECIENT.INTELLIGENCE_MULTIPLE, SKILL_EFFECIENT.DEBUFF],
    adjustment: [SKILL_ADJUSTMENT.INFANTRY, SKILL_ADJUSTMENT.ARCHER, SKILL_ADJUSTMENT.CAVALRY, SKILL_ADJUSTMENT.PIKEMAN],
    quality: SKILL_QUALITY.S,
    exchangable: false,
    hero: 'h00000134'
  },
  {
    id: 's00000135',
    name: '飞将明珠',
    name_en: 'feijiangmingzhu',
    desc: '对范围内的敌军共造成120%武力伤害，并对自身施加精准（无视闪避、抵挡、盾阵），持续10秒，技能冷却20秒。',
    desc_en: '',
    category: SKILL_CATEGORY.MAIN,
    level: 1,
    status: SKILL_STATUS.UNKNOWN,
    effecient: [SKILL_EFFECIENT.FORCE_MULTIPLE, SKILL_EFFECIENT.DEBUFF],
    adjustment: [SKILL_ADJUSTMENT.INFANTRY, SKILL_ADJUSTMENT.ARCHER, SKILL_ADJUSTMENT.CAVALRY, SKILL_ADJUSTMENT.PIKEMAN],
    quality: SKILL_QUALITY.S,
    exchangable: false,
    hero: 'h00000135'
  },
  {
    id: 's00000136',
    name: '高义傲骨',
    name_en: 'gaoyiaogu',
    desc: '对范围内的敌军共造成120%武力伤害，并对自身施加免疫沉默或者免疫缴械，持续10秒，技能冷却20秒。',
    desc_en: '',
    category: SKILL_CATEGORY.MAIN,
    level: 1,
    status: SKILL_STATUS.UNKNOWN,
    effecient: [SKILL_EFFECIENT.FORCE_MULTIPLE, SKILL_EFFECIENT.BUFF],
    adjustment: [SKILL_ADJUSTMENT.INFANTRY, SKILL_ADJUSTMENT.ARCHER, SKILL_ADJUSTMENT.CAVALRY, SKILL_ADJUSTMENT.PIKEMAN],
    quality: SKILL_QUALITY.S,
    exchangable: false,
    hero: 'h00000136'
  },
  {
    id: 's00000137',
    name: '八纳洞主',
    name_en: 'banadongzhu',
    desc: '对范围内的敌军共造成120%智力伤害，并使我方全体南蛮武将受到智力伤害降低20%，持续10秒，技能冷却20秒。',
    desc_en: '',
    category: SKILL_CATEGORY.MAIN,
    level: 1,
    status: SKILL_STATUS.UNKNOWN,
    effecient: [SKILL_EFFECIENT.INTELLIGENCE_MULTIPLE, SKILL_EFFECIENT.BUFF],
    adjustment: [SKILL_ADJUSTMENT.INFANTRY, SKILL_ADJUSTMENT.ARCHER, SKILL_ADJUSTMENT.CAVALRY, SKILL_ADJUSTMENT.PIKEMAN],
    quality: SKILL_QUALITY.S,
    exchangable: false,
    hero: 'h00000137'
  },
  {
    id: 's00000138',
    name: '好好先生',
    name_en: 'haohaoxiansheng',
    desc: '对范围内的敌军共造成120%智力伤害，并提高2名友方武将20%智力伤害，持续10秒，技能冷却20秒。',
    desc_en: '',
    category: SKILL_CATEGORY.MAIN,
    level: 1,
    status: SKILL_STATUS.UNKNOWN,
    effecient: [SKILL_EFFECIENT.INTELLIGENCE_MULTIPLE, SKILL_EFFECIENT.BUFF],
    adjustment: [SKILL_ADJUSTMENT.INFANTRY, SKILL_ADJUSTMENT.ARCHER, SKILL_ADJUSTMENT.CAVALRY, SKILL_ADJUSTMENT.PIKEMAN],
    quality: SKILL_QUALITY.S,
    exchangable: false,
    hero: 'h00000138'
  },
];